/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BulkRevokeTokensRequest model module.
 * @module model/BulkRevokeTokensRequest
 * @version 1.0.0
 */
class BulkRevokeTokensRequest {
    /**
     * Constructs a new <code>BulkRevokeTokensRequest</code>.
     * @alias module:model/BulkRevokeTokensRequest
     * @param tokenIds {Array.<String>} Array of token IDs to revoke.
     */
    constructor(tokenIds) { 
        
        BulkRevokeTokensRequest.initialize(this, tokenIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tokenIds) { 
        obj['token_ids'] = tokenIds;
    }

    /**
     * Constructs a <code>BulkRevokeTokensRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BulkRevokeTokensRequest} obj Optional instance to populate.
     * @return {module:model/BulkRevokeTokensRequest} The populated <code>BulkRevokeTokensRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BulkRevokeTokensRequest();

            if (data.hasOwnProperty('token_ids')) {
                obj['token_ids'] = ApiClient.convertToType(data['token_ids'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BulkRevokeTokensRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BulkRevokeTokensRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BulkRevokeTokensRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['token_ids'])) {
            throw new Error("Expected the field `token_ids` to be an array in the JSON data but got " + data['token_ids']);
        }

        return true;
    }


}

BulkRevokeTokensRequest.RequiredProperties = ["token_ids"];

/**
 * Array of token IDs to revoke.
 * @member {Array.<String>} token_ids
 */
BulkRevokeTokensRequest.prototype['token_ids'] = undefined;






export default BulkRevokeTokensRequest;

