/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BulkDeleteExternalGamesByIDsRequest model module.
 * @module model/BulkDeleteExternalGamesByIDsRequest
 * @version 1.0.0
 */
class BulkDeleteExternalGamesByIDsRequest {
    /**
     * Constructs a new <code>BulkDeleteExternalGamesByIDsRequest</code>.
     * @alias module:model/BulkDeleteExternalGamesByIDsRequest
     */
    constructor() { 
        
        BulkDeleteExternalGamesByIDsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BulkDeleteExternalGamesByIDsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BulkDeleteExternalGamesByIDsRequest} obj Optional instance to populate.
     * @return {module:model/BulkDeleteExternalGamesByIDsRequest} The populated <code>BulkDeleteExternalGamesByIDsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BulkDeleteExternalGamesByIDsRequest();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BulkDeleteExternalGamesByIDsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BulkDeleteExternalGamesByIDsRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['ids'])) {
            throw new Error("Expected the field `ids` to be an array in the JSON data but got " + data['ids']);
        }

        return true;
    }


}



/**
 * 
 * @member {Array.<Number>} ids
 */
BulkDeleteExternalGamesByIDsRequest.prototype['ids'] = undefined;






export default BulkDeleteExternalGamesByIDsRequest;

