/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner model module.
 * @module model/ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner
 * @version 1.0.0
 */
class ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner {
    /**
     * Constructs a new <code>ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner</code>.
     * @alias module:model/ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner
     */
    constructor() { 
        
        ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner} obj Optional instance to populate.
     * @return {module:model/ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner} The populated <code>ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner();

            if (data.hasOwnProperty('tier')) {
                obj['tier'] = ApiClient.convertToType(data['tier'], 'Number');
            }
            if (data.hasOwnProperty('winner_count')) {
                obj['winner_count'] = ApiClient.convertToType(data['winner_count'], 'Number');
            }
            if (data.hasOwnProperty('percentage')) {
                obj['percentage'] = ApiClient.convertToType(data['percentage'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * This field is required when <code>prize_tiers</code> is present. Must be at least 1.
 * @member {Number} tier
 */
ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner.prototype['tier'] = undefined;

/**
 * This field is required when <code>prize_tiers</code> is present. Must be at least 1.
 * @member {Number} winner_count
 */
ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner.prototype['winner_count'] = undefined;

/**
 * This field is required when <code>prize_tiers</code> is present. Must be at least 0.01. Must not be greater than 100.
 * @member {Number} percentage
 */
ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner.prototype['percentage'] = undefined;






export default ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner;

