/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigureLiveModeSettingsForAPoolRequest model module.
 * @module model/ConfigureLiveModeSettingsForAPoolRequest
 * @version 1.0.0
 */
class ConfigureLiveModeSettingsForAPoolRequest {
    /**
     * Constructs a new <code>ConfigureLiveModeSettingsForAPoolRequest</code>.
     * @alias module:model/ConfigureLiveModeSettingsForAPoolRequest
     * @param isLiveMode {Boolean} 
     */
    constructor(isLiveMode) { 
        
        ConfigureLiveModeSettingsForAPoolRequest.initialize(this, isLiveMode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, isLiveMode) { 
        obj['is_live_mode'] = isLiveMode;
    }

    /**
     * Constructs a <code>ConfigureLiveModeSettingsForAPoolRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigureLiveModeSettingsForAPoolRequest} obj Optional instance to populate.
     * @return {module:model/ConfigureLiveModeSettingsForAPoolRequest} The populated <code>ConfigureLiveModeSettingsForAPoolRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigureLiveModeSettingsForAPoolRequest();

            if (data.hasOwnProperty('is_live_mode')) {
                obj['is_live_mode'] = ApiClient.convertToType(data['is_live_mode'], 'Boolean');
            }
            if (data.hasOwnProperty('live_mode_window_seconds')) {
                obj['live_mode_window_seconds'] = ApiClient.convertToType(data['live_mode_window_seconds'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConfigureLiveModeSettingsForAPoolRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConfigureLiveModeSettingsForAPoolRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ConfigureLiveModeSettingsForAPoolRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ConfigureLiveModeSettingsForAPoolRequest.RequiredProperties = ["is_live_mode"];

/**
 * 
 * @member {Boolean} is_live_mode
 */
ConfigureLiveModeSettingsForAPoolRequest.prototype['is_live_mode'] = undefined;

/**
 * Must be at least 10. Must not be greater than 300.
 * @member {Number} live_mode_window_seconds
 */
ConfigureLiveModeSettingsForAPoolRequest.prototype['live_mode_window_seconds'] = undefined;






export default ConfigureLiveModeSettingsForAPoolRequest;

