/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateAStandaloneFreespin201ResponseData model module.
 * @module model/CreateAStandaloneFreespin201ResponseData
 * @version 1.0.0
 */
class CreateAStandaloneFreespin201ResponseData {
    /**
     * Constructs a new <code>CreateAStandaloneFreespin201ResponseData</code>.
     * @alias module:model/CreateAStandaloneFreespin201ResponseData
     */
    constructor() { 
        
        CreateAStandaloneFreespin201ResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateAStandaloneFreespin201ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateAStandaloneFreespin201ResponseData} obj Optional instance to populate.
     * @return {module:model/CreateAStandaloneFreespin201ResponseData} The populated <code>CreateAStandaloneFreespin201ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateAStandaloneFreespin201ResponseData();

            if (data.hasOwnProperty('freespin_id')) {
                obj['freespin_id'] = ApiClient.convertToType(data['freespin_id'], 'String');
            }
            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'String');
            }
            if (data.hasOwnProperty('game_id')) {
                obj['game_id'] = ApiClient.convertToType(data['game_id'], 'Number');
            }
            if (data.hasOwnProperty('total_count')) {
                obj['total_count'] = ApiClient.convertToType(data['total_count'], 'Number');
            }
            if (data.hasOwnProperty('bet_amount')) {
                obj['bet_amount'] = ApiClient.convertToType(data['bet_amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateAStandaloneFreespin201ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateAStandaloneFreespin201ResponseData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['freespin_id'] && !(typeof data['freespin_id'] === 'string' || data['freespin_id'] instanceof String)) {
            throw new Error("Expected the field `freespin_id` to be a primitive type in the JSON string but got " + data['freespin_id']);
        }
        // ensure the json data is a string
        if (data['player_id'] && !(typeof data['player_id'] === 'string' || data['player_id'] instanceof String)) {
            throw new Error("Expected the field `player_id` to be a primitive type in the JSON string but got " + data['player_id']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['expires_at'] && !(typeof data['expires_at'] === 'string' || data['expires_at'] instanceof String)) {
            throw new Error("Expected the field `expires_at` to be a primitive type in the JSON string but got " + data['expires_at']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {String} freespin_id
 */
CreateAStandaloneFreespin201ResponseData.prototype['freespin_id'] = undefined;

/**
 * @member {String} player_id
 */
CreateAStandaloneFreespin201ResponseData.prototype['player_id'] = undefined;

/**
 * @member {Number} game_id
 */
CreateAStandaloneFreespin201ResponseData.prototype['game_id'] = undefined;

/**
 * @member {Number} total_count
 */
CreateAStandaloneFreespin201ResponseData.prototype['total_count'] = undefined;

/**
 * @member {Number} bet_amount
 */
CreateAStandaloneFreespin201ResponseData.prototype['bet_amount'] = undefined;

/**
 * @member {String} currency
 */
CreateAStandaloneFreespin201ResponseData.prototype['currency'] = undefined;

/**
 * @member {String} expires_at
 */
CreateAStandaloneFreespin201ResponseData.prototype['expires_at'] = undefined;

/**
 * @member {String} status
 */
CreateAStandaloneFreespin201ResponseData.prototype['status'] = undefined;






export default CreateAStandaloneFreespin201ResponseData;

