/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Numeric from './Numeric';

/**
 * The CreateAStandaloneFreespinRequest model module.
 * @module model/CreateAStandaloneFreespinRequest
 * @version 1.0.0
 */
class CreateAStandaloneFreespinRequest {
    /**
     * Constructs a new <code>CreateAStandaloneFreespinRequest</code>.
     * @alias module:model/CreateAStandaloneFreespinRequest
     * @param gameId {Number} The internal game ID.
     * @param playerId {String} The player's ID in your system.
     * @param currency {String} Three-letter currency code (ISO 4217).
     * @param freespinId {String} Your unique identifier for this freespin campaign.
     * @param freespinCount {Number} Number of free spins to award (1-1000).
     */
    constructor(gameId, playerId, currency, freespinId, freespinCount) { 
        
        CreateAStandaloneFreespinRequest.initialize(this, gameId, playerId, currency, freespinId, freespinCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, gameId, playerId, currency, freespinId, freespinCount) { 
        obj['game_id'] = gameId;
        obj['player_id'] = playerId;
        obj['currency'] = currency;
        obj['freespin_id'] = freespinId;
        obj['freespin_count'] = freespinCount;
    }

    /**
     * Constructs a <code>CreateAStandaloneFreespinRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateAStandaloneFreespinRequest} obj Optional instance to populate.
     * @return {module:model/CreateAStandaloneFreespinRequest} The populated <code>CreateAStandaloneFreespinRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateAStandaloneFreespinRequest();

            if (data.hasOwnProperty('game_id')) {
                obj['game_id'] = ApiClient.convertToType(data['game_id'], 'Number');
            }
            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('freespin_id')) {
                obj['freespin_id'] = ApiClient.convertToType(data['freespin_id'], 'String');
            }
            if (data.hasOwnProperty('freespin_count')) {
                obj['freespin_count'] = ApiClient.convertToType(data['freespin_count'], 'Number');
            }
            if (data.hasOwnProperty('freespin_bet_amount')) {
                obj['freespin_bet_amount'] = ApiClient.convertToType(data['freespin_bet_amount'], Numeric);
            }
            if (data.hasOwnProperty('expire_days')) {
                obj['expire_days'] = ApiClient.convertToType(data['expire_days'], 'Number');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateAStandaloneFreespinRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateAStandaloneFreespinRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateAStandaloneFreespinRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['player_id'] && !(typeof data['player_id'] === 'string' || data['player_id'] instanceof String)) {
            throw new Error("Expected the field `player_id` to be a primitive type in the JSON string but got " + data['player_id']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['freespin_id'] && !(typeof data['freespin_id'] === 'string' || data['freespin_id'] instanceof String)) {
            throw new Error("Expected the field `freespin_id` to be a primitive type in the JSON string but got " + data['freespin_id']);
        }
        // ensure the json data is a string
        if (data['provider'] && !(typeof data['provider'] === 'string' || data['provider'] instanceof String)) {
            throw new Error("Expected the field `provider` to be a primitive type in the JSON string but got " + data['provider']);
        }

        return true;
    }


}

CreateAStandaloneFreespinRequest.RequiredProperties = ["game_id", "player_id", "currency", "freespin_id", "freespin_count"];

/**
 * The internal game ID.
 * @member {Number} game_id
 */
CreateAStandaloneFreespinRequest.prototype['game_id'] = undefined;

/**
 * The player's ID in your system.
 * @member {String} player_id
 */
CreateAStandaloneFreespinRequest.prototype['player_id'] = undefined;

/**
 * Three-letter currency code (ISO 4217).
 * @member {String} currency
 */
CreateAStandaloneFreespinRequest.prototype['currency'] = undefined;

/**
 * Your unique identifier for this freespin campaign.
 * @member {String} freespin_id
 */
CreateAStandaloneFreespinRequest.prototype['freespin_id'] = undefined;

/**
 * Number of free spins to award (1-1000).
 * @member {Number} freespin_count
 */
CreateAStandaloneFreespinRequest.prototype['freespin_count'] = undefined;

/**
 * optional Bet amount per free spin (0.01-1000).
 * @member {module:model/Numeric} freespin_bet_amount
 */
CreateAStandaloneFreespinRequest.prototype['freespin_bet_amount'] = undefined;

/**
 * optional Expiration in days, default 7, max 30.
 * @member {Number} expire_days
 */
CreateAStandaloneFreespinRequest.prototype['expire_days'] = undefined;

/**
 * optional Specific provider slug to use.
 * @member {String} provider
 */
CreateAStandaloneFreespinRequest.prototype['provider'] = undefined;






export default CreateAStandaloneFreespinRequest;

