/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateASingleExternalGameRequest model module.
 * @module model/CreateASingleExternalGameRequest
 * @version 1.0.0
 */
class CreateASingleExternalGameRequest {
    /**
     * Constructs a new <code>CreateASingleExternalGameRequest</code>.
     * @alias module:model/CreateASingleExternalGameRequest
     * @param externalGameId {String} Must not be greater than 100 characters.
     * @param name {String} Must not be greater than 255 characters.
     */
    constructor(externalGameId, name) { 
        
        CreateASingleExternalGameRequest.initialize(this, externalGameId, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, externalGameId, name) { 
        obj['external_game_id'] = externalGameId;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>CreateASingleExternalGameRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateASingleExternalGameRequest} obj Optional instance to populate.
     * @return {module:model/CreateASingleExternalGameRequest} The populated <code>CreateASingleExternalGameRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateASingleExternalGameRequest();

            if (data.hasOwnProperty('external_game_id')) {
                obj['external_game_id'] = ApiClient.convertToType(data['external_game_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('producer_name')) {
                obj['producer_name'] = ApiClient.convertToType(data['producer_name'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateASingleExternalGameRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateASingleExternalGameRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateASingleExternalGameRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['external_game_id'] && !(typeof data['external_game_id'] === 'string' || data['external_game_id'] instanceof String)) {
            throw new Error("Expected the field `external_game_id` to be a primitive type in the JSON string but got " + data['external_game_id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['producer_name'] && !(typeof data['producer_name'] === 'string' || data['producer_name'] instanceof String)) {
            throw new Error("Expected the field `producer_name` to be a primitive type in the JSON string but got " + data['producer_name']);
        }
        // ensure the json data is a string
        if (data['image_url'] && !(typeof data['image_url'] === 'string' || data['image_url'] instanceof String)) {
            throw new Error("Expected the field `image_url` to be a primitive type in the JSON string but got " + data['image_url']);
        }

        return true;
    }


}

CreateASingleExternalGameRequest.RequiredProperties = ["external_game_id", "name"];

/**
 * Must not be greater than 100 characters.
 * @member {String} external_game_id
 */
CreateASingleExternalGameRequest.prototype['external_game_id'] = undefined;

/**
 * Must not be greater than 255 characters.
 * @member {String} name
 */
CreateASingleExternalGameRequest.prototype['name'] = undefined;

/**
 * Must not be greater than 255 characters.
 * @member {String} producer_name
 */
CreateASingleExternalGameRequest.prototype['producer_name'] = undefined;

/**
 * Must be a valid URL. Must not be greater than 500 characters.
 * @member {String} image_url
 */
CreateASingleExternalGameRequest.prototype['image_url'] = undefined;

/**
 * 
 * @member {Object} metadata
 */
CreateASingleExternalGameRequest.prototype['metadata'] = undefined;






export default CreateASingleExternalGameRequest;

