/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateANewPromotionRequest model module.
 * @module model/CreateANewPromotionRequest
 * @version 1.0.0
 */
class CreateANewPromotionRequest {
    /**
     * Constructs a new <code>CreateANewPromotionRequest</code>.
     * @alias module:model/CreateANewPromotionRequest
     * @param name {String} Must not be greater than 255 characters.
     * @param promotionType {String} 
     * @param cycleType {String} 
     */
    constructor(name, promotionType, cycleType) { 
        
        CreateANewPromotionRequest.initialize(this, name, promotionType, cycleType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, promotionType, cycleType) { 
        obj['name'] = name;
        obj['promotion_type'] = promotionType;
        obj['cycle_type'] = cycleType;
    }

    /**
     * Constructs a <code>CreateANewPromotionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateANewPromotionRequest} obj Optional instance to populate.
     * @return {module:model/CreateANewPromotionRequest} The populated <code>CreateANewPromotionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateANewPromotionRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
            if (data.hasOwnProperty('terms_and_conditions')) {
                obj['terms_and_conditions'] = ApiClient.convertToType(data['terms_and_conditions'], 'String');
            }
            if (data.hasOwnProperty('promotion_type')) {
                obj['promotion_type'] = ApiClient.convertToType(data['promotion_type'], 'String');
            }
            if (data.hasOwnProperty('cycle_type')) {
                obj['cycle_type'] = ApiClient.convertToType(data['cycle_type'], 'String');
            }
            if (data.hasOwnProperty('starts_at')) {
                obj['starts_at'] = ApiClient.convertToType(data['starts_at'], 'String');
            }
            if (data.hasOwnProperty('ends_at')) {
                obj['ends_at'] = ApiClient.convertToType(data['ends_at'], 'String');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('prize_distribution')) {
                obj['prize_distribution'] = ApiClient.convertToType(data['prize_distribution'], Object);
            }
            if (data.hasOwnProperty('total_prize_pool')) {
                obj['total_prize_pool'] = ApiClient.convertToType(data['total_prize_pool'], 'Number');
            }
            if (data.hasOwnProperty('prize_currency')) {
                obj['prize_currency'] = ApiClient.convertToType(data['prize_currency'], 'String');
            }
            if (data.hasOwnProperty('winner_count')) {
                obj['winner_count'] = ApiClient.convertToType(data['winner_count'], 'Number');
            }
            if (data.hasOwnProperty('entry_config')) {
                obj['entry_config'] = ApiClient.convertToType(data['entry_config'], Object);
            }
            if (data.hasOwnProperty('game_filter_enabled')) {
                obj['game_filter_enabled'] = ApiClient.convertToType(data['game_filter_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('producer_filter_enabled')) {
                obj['producer_filter_enabled'] = ApiClient.convertToType(data['producer_filter_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('webhook_enabled')) {
                obj['webhook_enabled'] = ApiClient.convertToType(data['webhook_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('is_featured')) {
                obj['is_featured'] = ApiClient.convertToType(data['is_featured'], 'Boolean');
            }
            if (data.hasOwnProperty('game_ids')) {
                obj['game_ids'] = ApiClient.convertToType(data['game_ids'], ['Number']);
            }
            if (data.hasOwnProperty('producer_ids')) {
                obj['producer_ids'] = ApiClient.convertToType(data['producer_ids'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateANewPromotionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateANewPromotionRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateANewPromotionRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['image_url'] && !(typeof data['image_url'] === 'string' || data['image_url'] instanceof String)) {
            throw new Error("Expected the field `image_url` to be a primitive type in the JSON string but got " + data['image_url']);
        }
        // ensure the json data is a string
        if (data['terms_and_conditions'] && !(typeof data['terms_and_conditions'] === 'string' || data['terms_and_conditions'] instanceof String)) {
            throw new Error("Expected the field `terms_and_conditions` to be a primitive type in the JSON string but got " + data['terms_and_conditions']);
        }
        // ensure the json data is a string
        if (data['promotion_type'] && !(typeof data['promotion_type'] === 'string' || data['promotion_type'] instanceof String)) {
            throw new Error("Expected the field `promotion_type` to be a primitive type in the JSON string but got " + data['promotion_type']);
        }
        // ensure the json data is a string
        if (data['cycle_type'] && !(typeof data['cycle_type'] === 'string' || data['cycle_type'] instanceof String)) {
            throw new Error("Expected the field `cycle_type` to be a primitive type in the JSON string but got " + data['cycle_type']);
        }
        // ensure the json data is a string
        if (data['starts_at'] && !(typeof data['starts_at'] === 'string' || data['starts_at'] instanceof String)) {
            throw new Error("Expected the field `starts_at` to be a primitive type in the JSON string but got " + data['starts_at']);
        }
        // ensure the json data is a string
        if (data['ends_at'] && !(typeof data['ends_at'] === 'string' || data['ends_at'] instanceof String)) {
            throw new Error("Expected the field `ends_at` to be a primitive type in the JSON string but got " + data['ends_at']);
        }
        // ensure the json data is a string
        if (data['timezone'] && !(typeof data['timezone'] === 'string' || data['timezone'] instanceof String)) {
            throw new Error("Expected the field `timezone` to be a primitive type in the JSON string but got " + data['timezone']);
        }
        // ensure the json data is a string
        if (data['prize_currency'] && !(typeof data['prize_currency'] === 'string' || data['prize_currency'] instanceof String)) {
            throw new Error("Expected the field `prize_currency` to be a primitive type in the JSON string but got " + data['prize_currency']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['game_ids'])) {
            throw new Error("Expected the field `game_ids` to be an array in the JSON data but got " + data['game_ids']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['producer_ids'])) {
            throw new Error("Expected the field `producer_ids` to be an array in the JSON data but got " + data['producer_ids']);
        }

        return true;
    }


}

CreateANewPromotionRequest.RequiredProperties = ["name", "promotion_type", "cycle_type"];

/**
 * Must not be greater than 255 characters.
 * @member {String} name
 */
CreateANewPromotionRequest.prototype['name'] = undefined;

/**
 * 
 * @member {String} description
 */
CreateANewPromotionRequest.prototype['description'] = undefined;

/**
 * Must be a valid URL.
 * @member {String} image_url
 */
CreateANewPromotionRequest.prototype['image_url'] = undefined;

/**
 * 
 * @member {String} terms_and_conditions
 */
CreateANewPromotionRequest.prototype['terms_and_conditions'] = undefined;

/**
 * 
 * @member {String} promotion_type
 */
CreateANewPromotionRequest.prototype['promotion_type'] = undefined;

/**
 * 
 * @member {String} cycle_type
 */
CreateANewPromotionRequest.prototype['cycle_type'] = undefined;

/**
 * Must be a valid date.
 * @member {String} starts_at
 */
CreateANewPromotionRequest.prototype['starts_at'] = undefined;

/**
 * Must be a valid date. Must be a date after <code>starts_at</code>.
 * @member {String} ends_at
 */
CreateANewPromotionRequest.prototype['ends_at'] = undefined;

/**
 * 
 * @member {String} timezone
 */
CreateANewPromotionRequest.prototype['timezone'] = undefined;

/**
 * 
 * @member {Object} prize_distribution
 */
CreateANewPromotionRequest.prototype['prize_distribution'] = undefined;

/**
 * Must be at least 0.
 * @member {Number} total_prize_pool
 */
CreateANewPromotionRequest.prototype['total_prize_pool'] = undefined;

/**
 * Must be 3 characters.
 * @member {String} prize_currency
 */
CreateANewPromotionRequest.prototype['prize_currency'] = undefined;

/**
 * Must be at least 1.
 * @member {Number} winner_count
 */
CreateANewPromotionRequest.prototype['winner_count'] = undefined;

/**
 * 
 * @member {Object} entry_config
 */
CreateANewPromotionRequest.prototype['entry_config'] = undefined;

/**
 * 
 * @member {Boolean} game_filter_enabled
 */
CreateANewPromotionRequest.prototype['game_filter_enabled'] = undefined;

/**
 * 
 * @member {Boolean} producer_filter_enabled
 */
CreateANewPromotionRequest.prototype['producer_filter_enabled'] = undefined;

/**
 * 
 * @member {Boolean} webhook_enabled
 */
CreateANewPromotionRequest.prototype['webhook_enabled'] = undefined;

/**
 * 
 * @member {Boolean} is_featured
 */
CreateANewPromotionRequest.prototype['is_featured'] = undefined;

/**
 * The <code>id</code> of an existing record in the games table.
 * @member {Array.<Number>} game_ids
 */
CreateANewPromotionRequest.prototype['game_ids'] = undefined;

/**
 * The <code>id</code> of an existing record in the producers table.
 * @member {Array.<Number>} producer_ids
 */
CreateANewPromotionRequest.prototype['producer_ids'] = undefined;






export default CreateANewPromotionRequest;

