/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateATargetedPlayerConfigurationRequest model module.
 * @module model/CreateATargetedPlayerConfigurationRequest
 * @version 1.0.0
 */
class CreateATargetedPlayerConfigurationRequest {
    /**
     * Constructs a new <code>CreateATargetedPlayerConfigurationRequest</code>.
     * @alias module:model/CreateATargetedPlayerConfigurationRequest
     * @param playerId {String} Must not be greater than 100 characters.
     * @param poolType {module:model/CreateATargetedPlayerConfigurationRequest.PoolTypeEnum} 
     * @param currency {String} Must be 3 characters.
     * @param thresholdAmount {Number} Must be at least 1.
     */
    constructor(playerId, poolType, currency, thresholdAmount) { 
        
        CreateATargetedPlayerConfigurationRequest.initialize(this, playerId, poolType, currency, thresholdAmount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, playerId, poolType, currency, thresholdAmount) { 
        obj['player_id'] = playerId;
        obj['pool_type'] = poolType;
        obj['currency'] = currency;
        obj['threshold_amount'] = thresholdAmount;
    }

    /**
     * Constructs a <code>CreateATargetedPlayerConfigurationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateATargetedPlayerConfigurationRequest} obj Optional instance to populate.
     * @return {module:model/CreateATargetedPlayerConfigurationRequest} The populated <code>CreateATargetedPlayerConfigurationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateATargetedPlayerConfigurationRequest();

            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'String');
            }
            if (data.hasOwnProperty('pool_type')) {
                obj['pool_type'] = ApiClient.convertToType(data['pool_type'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('threshold_amount')) {
                obj['threshold_amount'] = ApiClient.convertToType(data['threshold_amount'], 'Number');
            }
            if (data.hasOwnProperty('threshold_variance')) {
                obj['threshold_variance'] = ApiClient.convertToType(data['threshold_variance'], 'Number');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateATargetedPlayerConfigurationRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateATargetedPlayerConfigurationRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateATargetedPlayerConfigurationRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['player_id'] && !(typeof data['player_id'] === 'string' || data['player_id'] instanceof String)) {
            throw new Error("Expected the field `player_id` to be a primitive type in the JSON string but got " + data['player_id']);
        }
        // ensure the json data is a string
        if (data['pool_type'] && !(typeof data['pool_type'] === 'string' || data['pool_type'] instanceof String)) {
            throw new Error("Expected the field `pool_type` to be a primitive type in the JSON string but got " + data['pool_type']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }

        return true;
    }


}

CreateATargetedPlayerConfigurationRequest.RequiredProperties = ["player_id", "pool_type", "currency", "threshold_amount"];

/**
 * Must not be greater than 100 characters.
 * @member {String} player_id
 */
CreateATargetedPlayerConfigurationRequest.prototype['player_id'] = undefined;

/**
 * 
 * @member {module:model/CreateATargetedPlayerConfigurationRequest.PoolTypeEnum} pool_type
 */
CreateATargetedPlayerConfigurationRequest.prototype['pool_type'] = undefined;

/**
 * Must be 3 characters.
 * @member {String} currency
 */
CreateATargetedPlayerConfigurationRequest.prototype['currency'] = undefined;

/**
 * Must be at least 1.
 * @member {Number} threshold_amount
 */
CreateATargetedPlayerConfigurationRequest.prototype['threshold_amount'] = undefined;

/**
 * Must be at least 0.
 * @member {Number} threshold_variance
 */
CreateATargetedPlayerConfigurationRequest.prototype['threshold_variance'] = undefined;

/**
 * 
 * @member {Object} metadata
 */
CreateATargetedPlayerConfigurationRequest.prototype['metadata'] = undefined;





/**
 * Allowed values for the <code>pool_type</code> property.
 * @enum {String}
 * @readonly
 */
CreateATargetedPlayerConfigurationRequest['PoolTypeEnum'] = {

    /**
     * value: "grand_prize"
     * @const
     */
    "grand_prize": "grand_prize",

    /**
     * value: "mega"
     * @const
     */
    "mega": "mega",

    /**
     * value: "major"
     * @const
     */
    "major": "major",

    /**
     * value: "minor"
     * @const
     */
    "minor": "minor",

    /**
     * value: "mini"
     * @const
     */
    "mini": "mini"
};



export default CreateATargetedPlayerConfigurationRequest;

