/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Datetime model module.
 * Represents a datetime value (ISO 8601 format).
 * @module model/Datetime
 * @version 1.0.0
 */
class Datetime {
    /**
     * Constructs a new <code>Datetime</code>.
     * A datetime value wrapper.
     * @alias module:model/Datetime
     * @param value {Date|String} The datetime value (Date object or ISO 8601 string)
     */
    constructor(value) {
        if (value instanceof Date) {
            this.value = value;
        } else if (typeof value === 'string') {
            this.value = new Date(value);
        } else {
            this.value = value;
        }
    }

    /**
     * Constructs a <code>Datetime</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object|Date|String} data The plain JavaScript object, Date, or ISO 8601 string.
     * @param {module:model/Datetime} obj Optional instance to populate.
     * @return {module:model/Datetime} The populated <code>Datetime</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data === null || data === undefined) {
            return null;
        }

        // Handle Date object
        if (data instanceof Date) {
            return new Datetime(data);
        }

        // Handle string (ISO 8601 format)
        if (typeof data === 'string') {
            return new Datetime(data);
        }

        // Handle object with value property
        if (typeof data === 'object' && data.hasOwnProperty('value')) {
            return new Datetime(data.value);
        }

        return new Datetime(data);
    }

    /**
     * Returns the Date value
     * @return {Date}
     */
    getValue() {
        return this.value;
    }

    /**
     * Returns the ISO 8601 string for JSON serialization
     * @return {String}
     */
    toJSON() {
        if (this.value instanceof Date) {
            return this.value.toISOString();
        }
        return this.value;
    }

    /**
     * Returns ISO 8601 string representation
     * @return {String}
     */
    toString() {
        if (this.value instanceof Date) {
            return this.value.toISOString();
        }
        return String(this.value);
    }
}

export default Datetime;
