/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Datetime from './Datetime';

/**
 * The GenerateAWidgetTokenRequest model module.
 * @module model/GenerateAWidgetTokenRequest
 * @version 1.0.0
 */
class GenerateAWidgetTokenRequest {
    /**
     * Constructs a new <code>GenerateAWidgetTokenRequest</code>.
     * @alias module:model/GenerateAWidgetTokenRequest
     * @param domainToken {String} The domain token from domain registration.
     */
    constructor(domainToken) { 
        
        GenerateAWidgetTokenRequest.initialize(this, domainToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, domainToken) { 
        obj['domain_token'] = domainToken;
    }

    /**
     * Constructs a <code>GenerateAWidgetTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenerateAWidgetTokenRequest} obj Optional instance to populate.
     * @return {module:model/GenerateAWidgetTokenRequest} The populated <code>GenerateAWidgetTokenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenerateAWidgetTokenRequest();

            if (data.hasOwnProperty('domain_token')) {
                obj['domain_token'] = ApiClient.convertToType(data['domain_token'], 'String');
            }
            if (data.hasOwnProperty('pool_types')) {
                obj['pool_types'] = ApiClient.convertToType(data['pool_types'], ['String']);
            }
            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], Datetime);
            }
            if (data.hasOwnProperty('configuration')) {
                obj['configuration'] = ApiClient.convertToType(data['configuration'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GenerateAWidgetTokenRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GenerateAWidgetTokenRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GenerateAWidgetTokenRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['domain_token'] && !(typeof data['domain_token'] === 'string' || data['domain_token'] instanceof String)) {
            throw new Error("Expected the field `domain_token` to be a primitive type in the JSON string but got " + data['domain_token']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['pool_types'])) {
            throw new Error("Expected the field `pool_types` to be an array in the JSON data but got " + data['pool_types']);
        }
        // ensure the json data is a string
        if (data['player_id'] && !(typeof data['player_id'] === 'string' || data['player_id'] instanceof String)) {
            throw new Error("Expected the field `player_id` to be a primitive type in the JSON string but got " + data['player_id']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }

        return true;
    }


}

GenerateAWidgetTokenRequest.RequiredProperties = ["domain_token"];

/**
 * The domain token from domain registration.
 * @member {String} domain_token
 */
GenerateAWidgetTokenRequest.prototype['domain_token'] = undefined;

/**
 * optional Allowed jackpot pool types. Default: [\"daily\",\"weekly\",\"monthly\"].
 * @member {Array.<String>} pool_types
 */
GenerateAWidgetTokenRequest.prototype['pool_types'] = undefined;

/**
 * optional Lock token to specific player (anonymous mode if omitted).
 * @member {String} player_id
 */
GenerateAWidgetTokenRequest.prototype['player_id'] = undefined;

/**
 * optional Player's currency (required if player_id provided).
 * @member {String} currency
 */
GenerateAWidgetTokenRequest.prototype['currency'] = undefined;

/**
 * optional Token expiration time (null = never expires).
 * @member {module:model/Datetime} expires_at
 */
GenerateAWidgetTokenRequest.prototype['expires_at'] = undefined;

/**
 * optional Additional widget configuration.
 * @member {Object} configuration
 */
GenerateAWidgetTokenRequest.prototype['configuration'] = undefined;






export default GenerateAWidgetTokenRequest;

