/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetGamesForAPoolTypeOrAllPoolTypesRequest model module.
 * @module model/GetGamesForAPoolTypeOrAllPoolTypesRequest
 * @version 1.0.0
 */
class GetGamesForAPoolTypeOrAllPoolTypesRequest {
    /**
     * Constructs a new <code>GetGamesForAPoolTypeOrAllPoolTypesRequest</code>.
     * @alias module:model/GetGamesForAPoolTypeOrAllPoolTypesRequest
     */
    constructor() { 
        
        GetGamesForAPoolTypeOrAllPoolTypesRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetGamesForAPoolTypeOrAllPoolTypesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetGamesForAPoolTypeOrAllPoolTypesRequest} obj Optional instance to populate.
     * @return {module:model/GetGamesForAPoolTypeOrAllPoolTypesRequest} The populated <code>GetGamesForAPoolTypeOrAllPoolTypesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetGamesForAPoolTypeOrAllPoolTypesRequest();

            if (data.hasOwnProperty('pool_type')) {
                obj['pool_type'] = ApiClient.convertToType(data['pool_type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetGamesForAPoolTypeOrAllPoolTypesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetGamesForAPoolTypeOrAllPoolTypesRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['pool_type'] && !(typeof data['pool_type'] === 'string' || data['pool_type'] instanceof String)) {
            throw new Error("Expected the field `pool_type` to be a primitive type in the JSON string but got " + data['pool_type']);
        }

        return true;
    }


}



/**
 * 
 * @member {module:model/GetGamesForAPoolTypeOrAllPoolTypesRequest.PoolTypeEnum} pool_type
 */
GetGamesForAPoolTypeOrAllPoolTypesRequest.prototype['pool_type'] = undefined;





/**
 * Allowed values for the <code>pool_type</code> property.
 * @enum {String}
 * @readonly
 */
GetGamesForAPoolTypeOrAllPoolTypesRequest['PoolTypeEnum'] = {

    /**
     * value: "daily"
     * @const
     */
    "daily": "daily",

    /**
     * value: "weekly"
     * @const
     */
    "weekly": "weekly",

    /**
     * value: "monthly"
     * @const
     */
    "monthly": "monthly",

    /**
     * value: "grand_prize"
     * @const
     */
    "grand_prize": "grand_prize"
};



export default GetGamesForAPoolTypeOrAllPoolTypesRequest;

