/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetMultiSessionStatus200ResponseDataGamesInner model module.
 * @module model/GetMultiSessionStatus200ResponseDataGamesInner
 * @version 1.0.0
 */
class GetMultiSessionStatus200ResponseDataGamesInner {
    /**
     * Constructs a new <code>GetMultiSessionStatus200ResponseDataGamesInner</code>.
     * @alias module:model/GetMultiSessionStatus200ResponseDataGamesInner
     */
    constructor() { 
        
        GetMultiSessionStatus200ResponseDataGamesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetMultiSessionStatus200ResponseDataGamesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetMultiSessionStatus200ResponseDataGamesInner} obj Optional instance to populate.
     * @return {module:model/GetMultiSessionStatus200ResponseDataGamesInner} The populated <code>GetMultiSessionStatus200ResponseDataGamesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetMultiSessionStatus200ResponseDataGamesInner();

            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('game_name')) {
                obj['game_name'] = ApiClient.convertToType(data['game_name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetMultiSessionStatus200ResponseDataGamesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetMultiSessionStatus200ResponseDataGamesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['game_name'] && !(typeof data['game_name'] === 'string' || data['game_name'] instanceof String)) {
            throw new Error("Expected the field `game_name` to be a primitive type in the JSON string but got " + data['game_name']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {Number} position
 */
GetMultiSessionStatus200ResponseDataGamesInner.prototype['position'] = undefined;

/**
 * @member {String} game_name
 */
GetMultiSessionStatus200ResponseDataGamesInner.prototype['game_name'] = undefined;

/**
 * @member {String} status
 */
GetMultiSessionStatus200ResponseDataGamesInner.prototype['status'] = undefined;






export default GetMultiSessionStatus200ResponseDataGamesInner;

