/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetPlayerContributionHistoryRequest model module.
 * @module model/GetPlayerContributionHistoryRequest
 * @version 1.0.0
 */
class GetPlayerContributionHistoryRequest {
    /**
     * Constructs a new <code>GetPlayerContributionHistoryRequest</code>.
     * @alias module:model/GetPlayerContributionHistoryRequest
     * @param playerId {String} Must not be greater than 100 characters.
     */
    constructor(playerId) { 
        
        GetPlayerContributionHistoryRequest.initialize(this, playerId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, playerId) { 
        obj['player_id'] = playerId;
    }

    /**
     * Constructs a <code>GetPlayerContributionHistoryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPlayerContributionHistoryRequest} obj Optional instance to populate.
     * @return {module:model/GetPlayerContributionHistoryRequest} The populated <code>GetPlayerContributionHistoryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPlayerContributionHistoryRequest();

            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetPlayerContributionHistoryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetPlayerContributionHistoryRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetPlayerContributionHistoryRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['player_id'] && !(typeof data['player_id'] === 'string' || data['player_id'] instanceof String)) {
            throw new Error("Expected the field `player_id` to be a primitive type in the JSON string but got " + data['player_id']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }

        return true;
    }


}

GetPlayerContributionHistoryRequest.RequiredProperties = ["player_id"];

/**
 * Must not be greater than 100 characters.
 * @member {String} player_id
 */
GetPlayerContributionHistoryRequest.prototype['player_id'] = undefined;

/**
 * Must be 3 characters.
 * @member {String} currency
 */
GetPlayerContributionHistoryRequest.prototype['currency'] = undefined;

/**
 * Must be at least 1. Must not be greater than 100.
 * @member {Number} limit
 */
GetPlayerContributionHistoryRequest.prototype['limit'] = undefined;

/**
 * Must be at least 0.
 * @member {Number} offset
 */
GetPlayerContributionHistoryRequest.prototype['offset'] = undefined;






export default GetPlayerContributionHistoryRequest;

