/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetSessionStatus200ResponseData from './GetSessionStatus200ResponseData';

/**
 * The GetSessionStatus200Response model module.
 * @module model/GetSessionStatus200Response
 * @version 1.0.0
 */
class GetSessionStatus200Response {
    /**
     * Constructs a new <code>GetSessionStatus200Response</code>.
     * @alias module:model/GetSessionStatus200Response
     */
    constructor() { 
        
        GetSessionStatus200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetSessionStatus200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSessionStatus200Response} obj Optional instance to populate.
     * @return {module:model/GetSessionStatus200Response} The populated <code>GetSessionStatus200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSessionStatus200Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = GetSessionStatus200ResponseData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetSessionStatus200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetSessionStatus200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          GetSessionStatus200ResponseData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {Boolean} success
 */
GetSessionStatus200Response.prototype['success'] = undefined;

/**
 * @member {module:model/GetSessionStatus200ResponseData} data
 */
GetSessionStatus200Response.prototype['data'] = undefined;






export default GetSessionStatus200Response;

