/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetSessionStatus200ResponseDataGame from './GetSessionStatus200ResponseDataGame';

/**
 * The GetSessionStatus200ResponseData model module.
 * @module model/GetSessionStatus200ResponseData
 * @version 1.0.0
 */
class GetSessionStatus200ResponseData {
    /**
     * Constructs a new <code>GetSessionStatus200ResponseData</code>.
     * @alias module:model/GetSessionStatus200ResponseData
     */
    constructor() { 
        
        GetSessionStatus200ResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetSessionStatus200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSessionStatus200ResponseData} obj Optional instance to populate.
     * @return {module:model/GetSessionStatus200ResponseData} The populated <code>GetSessionStatus200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSessionStatus200ResponseData();

            if (data.hasOwnProperty('session_id')) {
                obj['session_id'] = ApiClient.convertToType(data['session_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'String');
            }
            if (data.hasOwnProperty('game')) {
                obj['game'] = GetSessionStatus200ResponseDataGame.constructFromObject(data['game']);
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'String');
            }
            if (data.hasOwnProperty('last_activity')) {
                obj['last_activity'] = ApiClient.convertToType(data['last_activity'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetSessionStatus200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetSessionStatus200ResponseData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['session_id'] && !(typeof data['session_id'] === 'string' || data['session_id'] instanceof String)) {
            throw new Error("Expected the field `session_id` to be a primitive type in the JSON string but got " + data['session_id']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['player_id'] && !(typeof data['player_id'] === 'string' || data['player_id'] instanceof String)) {
            throw new Error("Expected the field `player_id` to be a primitive type in the JSON string but got " + data['player_id']);
        }
        // validate the optional field `game`
        if (data['game']) { // data not null
          GetSessionStatus200ResponseDataGame.validateJSON(data['game']);
        }
        // ensure the json data is a string
        if (data['started_at'] && !(typeof data['started_at'] === 'string' || data['started_at'] instanceof String)) {
            throw new Error("Expected the field `started_at` to be a primitive type in the JSON string but got " + data['started_at']);
        }
        // ensure the json data is a string
        if (data['last_activity'] && !(typeof data['last_activity'] === 'string' || data['last_activity'] instanceof String)) {
            throw new Error("Expected the field `last_activity` to be a primitive type in the JSON string but got " + data['last_activity']);
        }

        return true;
    }


}



/**
 * @member {String} session_id
 */
GetSessionStatus200ResponseData.prototype['session_id'] = undefined;

/**
 * @member {String} status
 */
GetSessionStatus200ResponseData.prototype['status'] = undefined;

/**
 * @member {String} player_id
 */
GetSessionStatus200ResponseData.prototype['player_id'] = undefined;

/**
 * @member {module:model/GetSessionStatus200ResponseDataGame} game
 */
GetSessionStatus200ResponseData.prototype['game'] = undefined;

/**
 * @member {String} started_at
 */
GetSessionStatus200ResponseData.prototype['started_at'] = undefined;

/**
 * @member {String} last_activity
 */
GetSessionStatus200ResponseData.prototype['last_activity'] = undefined;






export default GetSessionStatus200ResponseData;

