/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetSessionStatus200ResponseDataGame from './GetSessionStatus200ResponseDataGame';

/**
 * The GetTransactionHistory200ResponseDataInner model module.
 * @module model/GetTransactionHistory200ResponseDataInner
 * @version 1.0.0
 */
class GetTransactionHistory200ResponseDataInner {
    /**
     * Constructs a new <code>GetTransactionHistory200ResponseDataInner</code>.
     * @alias module:model/GetTransactionHistory200ResponseDataInner
     */
    constructor() { 
        
        GetTransactionHistory200ResponseDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetTransactionHistory200ResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTransactionHistory200ResponseDataInner} obj Optional instance to populate.
     * @return {module:model/GetTransactionHistory200ResponseDataInner} The populated <code>GetTransactionHistory200ResponseDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTransactionHistory200ResponseDataInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'String');
            }
            if (data.hasOwnProperty('game')) {
                obj['game'] = GetSessionStatus200ResponseDataGame.constructFromObject(data['game']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('balance_after')) {
                obj['balance_after'] = ApiClient.convertToType(data['balance_after'], 'Number');
            }
            if (data.hasOwnProperty('round_id')) {
                obj['round_id'] = ApiClient.convertToType(data['round_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetTransactionHistory200ResponseDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetTransactionHistory200ResponseDataInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['player_id'] && !(typeof data['player_id'] === 'string' || data['player_id'] instanceof String)) {
            throw new Error("Expected the field `player_id` to be a primitive type in the JSON string but got " + data['player_id']);
        }
        // validate the optional field `game`
        if (data['game']) { // data not null
          GetSessionStatus200ResponseDataGame.validateJSON(data['game']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['round_id'] && !(typeof data['round_id'] === 'string' || data['round_id'] instanceof String)) {
            throw new Error("Expected the field `round_id` to be a primitive type in the JSON string but got " + data['round_id']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
GetTransactionHistory200ResponseDataInner.prototype['id'] = undefined;

/**
 * @member {String} player_id
 */
GetTransactionHistory200ResponseDataInner.prototype['player_id'] = undefined;

/**
 * @member {module:model/GetSessionStatus200ResponseDataGame} game
 */
GetTransactionHistory200ResponseDataInner.prototype['game'] = undefined;

/**
 * @member {String} type
 */
GetTransactionHistory200ResponseDataInner.prototype['type'] = undefined;

/**
 * @member {Number} amount
 */
GetTransactionHistory200ResponseDataInner.prototype['amount'] = undefined;

/**
 * @member {String} currency
 */
GetTransactionHistory200ResponseDataInner.prototype['currency'] = undefined;

/**
 * @member {Number} balance_after
 */
GetTransactionHistory200ResponseDataInner.prototype['balance_after'] = undefined;

/**
 * @member {String} round_id
 */
GetTransactionHistory200ResponseDataInner.prototype['round_id'] = undefined;

/**
 * @member {String} status
 */
GetTransactionHistory200ResponseDataInner.prototype['status'] = undefined;

/**
 * @member {String} created_at
 */
GetTransactionHistory200ResponseDataInner.prototype['created_at'] = undefined;






export default GetTransactionHistory200ResponseDataInner;

