/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetTransactionHistory200ResponseMetaSummary from './GetTransactionHistory200ResponseMetaSummary';

/**
 * The GetTransactionHistory200ResponseMeta model module.
 * @module model/GetTransactionHistory200ResponseMeta
 * @version 1.0.0
 */
class GetTransactionHistory200ResponseMeta {
    /**
     * Constructs a new <code>GetTransactionHistory200ResponseMeta</code>.
     * @alias module:model/GetTransactionHistory200ResponseMeta
     */
    constructor() { 
        
        GetTransactionHistory200ResponseMeta.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetTransactionHistory200ResponseMeta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTransactionHistory200ResponseMeta} obj Optional instance to populate.
     * @return {module:model/GetTransactionHistory200ResponseMeta} The populated <code>GetTransactionHistory200ResponseMeta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTransactionHistory200ResponseMeta();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = GetTransactionHistory200ResponseMetaSummary.constructFromObject(data['summary']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetTransactionHistory200ResponseMeta</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetTransactionHistory200ResponseMeta</code>.
     */
    static validateJSON(data) {
        // validate the optional field `summary`
        if (data['summary']) { // data not null
          GetTransactionHistory200ResponseMetaSummary.validateJSON(data['summary']);
        }

        return true;
    }


}



/**
 * @member {Number} total
 */
GetTransactionHistory200ResponseMeta.prototype['total'] = undefined;

/**
 * @member {Number} limit
 */
GetTransactionHistory200ResponseMeta.prototype['limit'] = undefined;

/**
 * @member {Number} offset
 */
GetTransactionHistory200ResponseMeta.prototype['offset'] = undefined;

/**
 * @member {module:model/GetTransactionHistory200ResponseMetaSummary} summary
 */
GetTransactionHistory200ResponseMeta.prototype['summary'] = undefined;






export default GetTransactionHistory200ResponseMeta;

