/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetTransactionHistory200ResponseMetaSummary model module.
 * @module model/GetTransactionHistory200ResponseMetaSummary
 * @version 1.0.0
 */
class GetTransactionHistory200ResponseMetaSummary {
    /**
     * Constructs a new <code>GetTransactionHistory200ResponseMetaSummary</code>.
     * @alias module:model/GetTransactionHistory200ResponseMetaSummary
     */
    constructor() { 
        
        GetTransactionHistory200ResponseMetaSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetTransactionHistory200ResponseMetaSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTransactionHistory200ResponseMetaSummary} obj Optional instance to populate.
     * @return {module:model/GetTransactionHistory200ResponseMetaSummary} The populated <code>GetTransactionHistory200ResponseMetaSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTransactionHistory200ResponseMetaSummary();

            if (data.hasOwnProperty('total_bets')) {
                obj['total_bets'] = ApiClient.convertToType(data['total_bets'], 'Number');
            }
            if (data.hasOwnProperty('total_wins')) {
                obj['total_wins'] = ApiClient.convertToType(data['total_wins'], 'Number');
            }
            if (data.hasOwnProperty('net_result')) {
                obj['net_result'] = ApiClient.convertToType(data['net_result'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetTransactionHistory200ResponseMetaSummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetTransactionHistory200ResponseMetaSummary</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} total_bets
 */
GetTransactionHistory200ResponseMetaSummary.prototype['total_bets'] = undefined;

/**
 * @member {Number} total_wins
 */
GetTransactionHistory200ResponseMetaSummary.prototype['total_wins'] = undefined;

/**
 * @member {Number} net_result
 */
GetTransactionHistory200ResponseMetaSummary.prototype['net_result'] = undefined;






export default GetTransactionHistory200ResponseMetaSummary;

