/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ImportExternalGamesFromJSONPasteRequestGamesInner from './ImportExternalGamesFromJSONPasteRequestGamesInner';

/**
 * The ImportExternalGamesFromJSONPasteRequest model module.
 * @module model/ImportExternalGamesFromJSONPasteRequest
 * @version 1.0.0
 */
class ImportExternalGamesFromJSONPasteRequest {
    /**
     * Constructs a new <code>ImportExternalGamesFromJSONPasteRequest</code>.
     * @alias module:model/ImportExternalGamesFromJSONPasteRequest
     * @param games {Array.<module:model/ImportExternalGamesFromJSONPasteRequestGamesInner>} Must have at least 1 items. Must not have more than 1000 items.
     */
    constructor(games) { 
        
        ImportExternalGamesFromJSONPasteRequest.initialize(this, games);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, games) { 
        obj['games'] = games;
    }

    /**
     * Constructs a <code>ImportExternalGamesFromJSONPasteRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ImportExternalGamesFromJSONPasteRequest} obj Optional instance to populate.
     * @return {module:model/ImportExternalGamesFromJSONPasteRequest} The populated <code>ImportExternalGamesFromJSONPasteRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImportExternalGamesFromJSONPasteRequest();

            if (data.hasOwnProperty('games')) {
                obj['games'] = ApiClient.convertToType(data['games'], [ImportExternalGamesFromJSONPasteRequestGamesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ImportExternalGamesFromJSONPasteRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ImportExternalGamesFromJSONPasteRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ImportExternalGamesFromJSONPasteRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['games']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['games'])) {
                throw new Error("Expected the field `games` to be an array in the JSON data but got " + data['games']);
            }
            // validate the optional field `games` (array)
            for (const item of data['games']) {
                ImportExternalGamesFromJSONPasteRequestGamesInner.validateJSON(item);
            };
        }

        return true;
    }


}

ImportExternalGamesFromJSONPasteRequest.RequiredProperties = ["games"];

/**
 * Must have at least 1 items. Must not have more than 1000 items.
 * @member {Array.<module:model/ImportExternalGamesFromJSONPasteRequestGamesInner>} games
 */
ImportExternalGamesFromJSONPasteRequest.prototype['games'] = undefined;






export default ImportExternalGamesFromJSONPasteRequest;

