/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListGamesRequest model module.
 * @module model/ListGamesRequest
 * @version 1.0.0
 */
class ListGamesRequest {
    /**
     * Constructs a new <code>ListGamesRequest</code>.
     * @alias module:model/ListGamesRequest
     */
    constructor() { 
        
        ListGamesRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListGamesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListGamesRequest} obj Optional instance to populate.
     * @return {module:model/ListGamesRequest} The populated <code>ListGamesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListGamesRequest();

            if (data.hasOwnProperty('search')) {
                obj['search'] = ApiClient.convertToType(data['search'], 'String');
            }
            if (data.hasOwnProperty('producer_id')) {
                obj['producer_id'] = ApiClient.convertToType(data['producer_id'], 'Number');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('per_page')) {
                obj['per_page'] = ApiClient.convertToType(data['per_page'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListGamesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListGamesRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['search'] && !(typeof data['search'] === 'string' || data['search'] instanceof String)) {
            throw new Error("Expected the field `search` to be a primitive type in the JSON string but got " + data['search']);
        }
        // ensure the json data is a string
        if (data['provider'] && !(typeof data['provider'] === 'string' || data['provider'] instanceof String)) {
            throw new Error("Expected the field `provider` to be a primitive type in the JSON string but got " + data['provider']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['per_page'] && !(typeof data['per_page'] === 'string' || data['per_page'] instanceof String)) {
            throw new Error("Expected the field `per_page` to be a primitive type in the JSON string but got " + data['per_page']);
        }

        return true;
    }


}



/**
 * Must not be greater than 255 characters.
 * @member {String} search
 */
ListGamesRequest.prototype['search'] = undefined;

/**
 * The <code>id</code> of an existing record in the game_producers table.
 * @member {Number} producer_id
 */
ListGamesRequest.prototype['producer_id'] = undefined;

/**
 * The <code>slug</code> of an existing record in the providers table.
 * @member {String} provider
 */
ListGamesRequest.prototype['provider'] = undefined;

/**
 * 
 * @member {module:model/ListGamesRequest.TypeEnum} type
 */
ListGamesRequest.prototype['type'] = undefined;

/**
 * Must match the regex /^(all.
 * @member {String} per_page
 */
ListGamesRequest.prototype['per_page'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
ListGamesRequest['TypeEnum'] = {

    /**
     * value: "slot"
     * @const
     */
    "slot": "slot",

    /**
     * value: "table"
     * @const
     */
    "table": "table",

    /**
     * value: "live"
     * @const
     */
    "live": "live"
};



export default ListGamesRequest;

