/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListWidgetTokens200ResponseDataInner model module.
 * @module model/ListWidgetTokens200ResponseDataInner
 * @version 1.0.0
 */
class ListWidgetTokens200ResponseDataInner {
    /**
     * Constructs a new <code>ListWidgetTokens200ResponseDataInner</code>.
     * @alias module:model/ListWidgetTokens200ResponseDataInner
     */
    constructor() { 
        
        ListWidgetTokens200ResponseDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListWidgetTokens200ResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListWidgetTokens200ResponseDataInner} obj Optional instance to populate.
     * @return {module:model/ListWidgetTokens200ResponseDataInner} The populated <code>ListWidgetTokens200ResponseDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListWidgetTokens200ResponseDataInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('widget_type')) {
                obj['widget_type'] = ApiClient.convertToType(data['widget_type'], 'String');
            }
            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('allowed_pool_types')) {
                obj['allowed_pool_types'] = ApiClient.convertToType(data['allowed_pool_types'], ['String']);
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'String');
            }
            if (data.hasOwnProperty('last_used_at')) {
                obj['last_used_at'] = ApiClient.convertToType(data['last_used_at'], 'String');
            }
            if (data.hasOwnProperty('request_count')) {
                obj['request_count'] = ApiClient.convertToType(data['request_count'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListWidgetTokens200ResponseDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListWidgetTokens200ResponseDataInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['domain'] && !(typeof data['domain'] === 'string' || data['domain'] instanceof String)) {
            throw new Error("Expected the field `domain` to be a primitive type in the JSON string but got " + data['domain']);
        }
        // ensure the json data is a string
        if (data['widget_type'] && !(typeof data['widget_type'] === 'string' || data['widget_type'] instanceof String)) {
            throw new Error("Expected the field `widget_type` to be a primitive type in the JSON string but got " + data['widget_type']);
        }
        // ensure the json data is a string
        if (data['player_id'] && !(typeof data['player_id'] === 'string' || data['player_id'] instanceof String)) {
            throw new Error("Expected the field `player_id` to be a primitive type in the JSON string but got " + data['player_id']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['allowed_pool_types'])) {
            throw new Error("Expected the field `allowed_pool_types` to be an array in the JSON data but got " + data['allowed_pool_types']);
        }
        // ensure the json data is a string
        if (data['expires_at'] && !(typeof data['expires_at'] === 'string' || data['expires_at'] instanceof String)) {
            throw new Error("Expected the field `expires_at` to be a primitive type in the JSON string but got " + data['expires_at']);
        }
        // ensure the json data is a string
        if (data['last_used_at'] && !(typeof data['last_used_at'] === 'string' || data['last_used_at'] instanceof String)) {
            throw new Error("Expected the field `last_used_at` to be a primitive type in the JSON string but got " + data['last_used_at']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
ListWidgetTokens200ResponseDataInner.prototype['id'] = undefined;

/**
 * @member {String} domain
 */
ListWidgetTokens200ResponseDataInner.prototype['domain'] = undefined;

/**
 * @member {String} widget_type
 */
ListWidgetTokens200ResponseDataInner.prototype['widget_type'] = undefined;

/**
 * @member {String} player_id
 */
ListWidgetTokens200ResponseDataInner.prototype['player_id'] = undefined;

/**
 * @member {String} currency
 */
ListWidgetTokens200ResponseDataInner.prototype['currency'] = undefined;

/**
 * @member {Array.<String>} allowed_pool_types
 */
ListWidgetTokens200ResponseDataInner.prototype['allowed_pool_types'] = undefined;

/**
 * @member {Boolean} is_active
 */
ListWidgetTokens200ResponseDataInner.prototype['is_active'] = undefined;

/**
 * @member {String} expires_at
 */
ListWidgetTokens200ResponseDataInner.prototype['expires_at'] = undefined;

/**
 * @member {String} last_used_at
 */
ListWidgetTokens200ResponseDataInner.prototype['last_used_at'] = undefined;

/**
 * @member {Number} request_count
 */
ListWidgetTokens200ResponseDataInner.prototype['request_count'] = undefined;

/**
 * @member {String} created_at
 */
ListWidgetTokens200ResponseDataInner.prototype['created_at'] = undefined;






export default ListWidgetTokens200ResponseDataInner;

