/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListGames200ResponseMeta model module.
 * @module model/ListGames200ResponseMeta
 * @version 1.0.0
 */
class ListGames200ResponseMeta {
    /**
     * Constructs a new <code>ListGames200ResponseMeta</code>.
     * @alias module:model/ListGames200ResponseMeta
     */
    constructor() { 
        
        ListGames200ResponseMeta.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListGames200ResponseMeta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListGames200ResponseMeta} obj Optional instance to populate.
     * @return {module:model/ListGames200ResponseMeta} The populated <code>ListGames200ResponseMeta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListGames200ResponseMeta();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListGames200ResponseMeta</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListGames200ResponseMeta</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} total
 */
ListGames200ResponseMeta.prototype['total'] = undefined;






export default ListGames200ResponseMeta;

