/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListRegisteredDomains200ResponseDataInner model module.
 * @module model/ListRegisteredDomains200ResponseDataInner
 * @version 1.0.0
 */
class ListRegisteredDomains200ResponseDataInner {
    /**
     * Constructs a new <code>ListRegisteredDomains200ResponseDataInner</code>.
     * @alias module:model/ListRegisteredDomains200ResponseDataInner
     */
    constructor() { 
        
        ListRegisteredDomains200ResponseDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListRegisteredDomains200ResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListRegisteredDomains200ResponseDataInner} obj Optional instance to populate.
     * @return {module:model/ListRegisteredDomains200ResponseDataInner} The populated <code>ListRegisteredDomains200ResponseDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListRegisteredDomains200ResponseDataInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('domain_token')) {
                obj['domain_token'] = ApiClient.convertToType(data['domain_token'], 'String');
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
            if (data.hasOwnProperty('allowed_widgets')) {
                obj['allowed_widgets'] = ApiClient.convertToType(data['allowed_widgets'], ['String']);
            }
            if (data.hasOwnProperty('tokens_count')) {
                obj['tokens_count'] = ApiClient.convertToType(data['tokens_count'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListRegisteredDomains200ResponseDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListRegisteredDomains200ResponseDataInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['domain'] && !(typeof data['domain'] === 'string' || data['domain'] instanceof String)) {
            throw new Error("Expected the field `domain` to be a primitive type in the JSON string but got " + data['domain']);
        }
        // ensure the json data is a string
        if (data['domain_token'] && !(typeof data['domain_token'] === 'string' || data['domain_token'] instanceof String)) {
            throw new Error("Expected the field `domain_token` to be a primitive type in the JSON string but got " + data['domain_token']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['allowed_widgets'])) {
            throw new Error("Expected the field `allowed_widgets` to be an array in the JSON data but got " + data['allowed_widgets']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
ListRegisteredDomains200ResponseDataInner.prototype['id'] = undefined;

/**
 * @member {String} domain
 */
ListRegisteredDomains200ResponseDataInner.prototype['domain'] = undefined;

/**
 * @member {String} domain_token
 */
ListRegisteredDomains200ResponseDataInner.prototype['domain_token'] = undefined;

/**
 * @member {Boolean} is_active
 */
ListRegisteredDomains200ResponseDataInner.prototype['is_active'] = undefined;

/**
 * @member {Array.<String>} allowed_widgets
 */
ListRegisteredDomains200ResponseDataInner.prototype['allowed_widgets'] = undefined;

/**
 * @member {Number} tokens_count
 */
ListRegisteredDomains200ResponseDataInner.prototype['tokens_count'] = undefined;

/**
 * @member {String} created_at
 */
ListRegisteredDomains200ResponseDataInner.prototype['created_at'] = undefined;






export default ListRegisteredDomains200ResponseDataInner;

