/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListRegisteredDomains200ResponseDataInner from './ListRegisteredDomains200ResponseDataInner';

/**
 * The ListRegisteredDomains200Response model module.
 * @module model/ListRegisteredDomains200Response
 * @version 1.0.0
 */
class ListRegisteredDomains200Response {
    /**
     * Constructs a new <code>ListRegisteredDomains200Response</code>.
     * @alias module:model/ListRegisteredDomains200Response
     */
    constructor() { 
        
        ListRegisteredDomains200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListRegisteredDomains200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListRegisteredDomains200Response} obj Optional instance to populate.
     * @return {module:model/ListRegisteredDomains200Response} The populated <code>ListRegisteredDomains200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListRegisteredDomains200Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [ListRegisteredDomains200ResponseDataInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListRegisteredDomains200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListRegisteredDomains200Response</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                ListRegisteredDomains200ResponseDataInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Boolean} success
 */
ListRegisteredDomains200Response.prototype['success'] = undefined;

/**
 * @member {Array.<module:model/ListRegisteredDomains200ResponseDataInner>} data
 */
ListRegisteredDomains200Response.prototype['data'] = undefined;






export default ListRegisteredDomains200Response;

