/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListExternalGamesForOperatorRequest model module.
 * @module model/ListExternalGamesForOperatorRequest
 * @version 1.0.0
 */
class ListExternalGamesForOperatorRequest {
    /**
     * Constructs a new <code>ListExternalGamesForOperatorRequest</code>.
     * @alias module:model/ListExternalGamesForOperatorRequest
     */
    constructor() { 
        
        ListExternalGamesForOperatorRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListExternalGamesForOperatorRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListExternalGamesForOperatorRequest} obj Optional instance to populate.
     * @return {module:model/ListExternalGamesForOperatorRequest} The populated <code>ListExternalGamesForOperatorRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListExternalGamesForOperatorRequest();

            if (data.hasOwnProperty('search')) {
                obj['search'] = ApiClient.convertToType(data['search'], 'String');
            }
            if (data.hasOwnProperty('producer_name')) {
                obj['producer_name'] = ApiClient.convertToType(data['producer_name'], 'String');
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
            if (data.hasOwnProperty('per_page')) {
                obj['per_page'] = ApiClient.convertToType(data['per_page'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListExternalGamesForOperatorRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListExternalGamesForOperatorRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['search'] && !(typeof data['search'] === 'string' || data['search'] instanceof String)) {
            throw new Error("Expected the field `search` to be a primitive type in the JSON string but got " + data['search']);
        }
        // ensure the json data is a string
        if (data['producer_name'] && !(typeof data['producer_name'] === 'string' || data['producer_name'] instanceof String)) {
            throw new Error("Expected the field `producer_name` to be a primitive type in the JSON string but got " + data['producer_name']);
        }

        return true;
    }


}



/**
 * Must not be greater than 255 characters.
 * @member {String} search
 */
ListExternalGamesForOperatorRequest.prototype['search'] = undefined;

/**
 * Must not be greater than 255 characters.
 * @member {String} producer_name
 */
ListExternalGamesForOperatorRequest.prototype['producer_name'] = undefined;

/**
 * 
 * @member {Boolean} is_active
 */
ListExternalGamesForOperatorRequest.prototype['is_active'] = undefined;

/**
 * Must be at least 1. Must not be greater than 100.
 * @member {Number} per_page
 */
ListExternalGamesForOperatorRequest.prototype['per_page'] = undefined;






export default ListExternalGamesForOperatorRequest;

