/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ManageGamesForAPromotionRequest model module.
 * @module model/ManageGamesForAPromotionRequest
 * @version 1.0.0
 */
class ManageGamesForAPromotionRequest {
    /**
     * Constructs a new <code>ManageGamesForAPromotionRequest</code>.
     * @alias module:model/ManageGamesForAPromotionRequest
     */
    constructor() { 
        
        ManageGamesForAPromotionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ManageGamesForAPromotionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ManageGamesForAPromotionRequest} obj Optional instance to populate.
     * @return {module:model/ManageGamesForAPromotionRequest} The populated <code>ManageGamesForAPromotionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ManageGamesForAPromotionRequest();

            if (data.hasOwnProperty('game_ids')) {
                obj['game_ids'] = ApiClient.convertToType(data['game_ids'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ManageGamesForAPromotionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ManageGamesForAPromotionRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['game_ids'])) {
            throw new Error("Expected the field `game_ids` to be an array in the JSON data but got " + data['game_ids']);
        }

        return true;
    }


}



/**
 * The <code>id</code> of an existing record in the games table.
 * @member {Array.<Number>} game_ids
 */
ManageGamesForAPromotionRequest.prototype['game_ids'] = undefined;






export default ManageGamesForAPromotionRequest;

