/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Numeric model module.
 * Represents a numeric value (used for decimal amounts like bet amounts).
 * @module model/Numeric
 * @version 1.0.0
 */
class Numeric {
    /**
     * Constructs a new <code>Numeric</code>.
     * A numeric value wrapper for decimal amounts.
     * @alias module:model/Numeric
     * @param value {Number} The numeric value
     */
    constructor(value) {
        this.value = value;
    }

    /**
     * Constructs a <code>Numeric</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object|Number|String} data The plain JavaScript object or primitive value.
     * @param {module:model/Numeric} obj Optional instance to populate.
     * @return {module:model/Numeric} The populated <code>Numeric</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data === null || data === undefined) {
            return null;
        }

        // Handle primitive number or string input
        if (typeof data === 'number' || typeof data === 'string') {
            return new Numeric(parseFloat(data));
        }

        // Handle object with value property
        if (typeof data === 'object' && data.hasOwnProperty('value')) {
            return new Numeric(parseFloat(data.value));
        }

        return new Numeric(parseFloat(data));
    }

    /**
     * Returns the numeric value
     * @return {Number}
     */
    getValue() {
        return this.value;
    }

    /**
     * Returns the primitive value for JSON serialization
     * @return {Number}
     */
    toJSON() {
        return this.value;
    }

    /**
     * Returns string representation
     * @return {String}
     */
    toString() {
        return String(this.value);
    }
}

export default Numeric;
