/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RegenerateDomainToken200ResponseData from './RegenerateDomainToken200ResponseData';

/**
 * The RegenerateDomainToken200Response model module.
 * @module model/RegenerateDomainToken200Response
 * @version 1.0.0
 */
class RegenerateDomainToken200Response {
    /**
     * Constructs a new <code>RegenerateDomainToken200Response</code>.
     * @alias module:model/RegenerateDomainToken200Response
     */
    constructor() { 
        
        RegenerateDomainToken200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RegenerateDomainToken200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegenerateDomainToken200Response} obj Optional instance to populate.
     * @return {module:model/RegenerateDomainToken200Response} The populated <code>RegenerateDomainToken200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegenerateDomainToken200Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = RegenerateDomainToken200ResponseData.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RegenerateDomainToken200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RegenerateDomainToken200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          RegenerateDomainToken200ResponseData.validateJSON(data['data']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}



/**
 * @member {Boolean} success
 */
RegenerateDomainToken200Response.prototype['success'] = undefined;

/**
 * @member {module:model/RegenerateDomainToken200ResponseData} data
 */
RegenerateDomainToken200Response.prototype['data'] = undefined;

/**
 * @member {String} message
 */
RegenerateDomainToken200Response.prototype['message'] = undefined;






export default RegenerateDomainToken200Response;

