/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegenerateDomainToken200ResponseData model module.
 * @module model/RegenerateDomainToken200ResponseData
 * @version 1.0.0
 */
class RegenerateDomainToken200ResponseData {
    /**
     * Constructs a new <code>RegenerateDomainToken200ResponseData</code>.
     * @alias module:model/RegenerateDomainToken200ResponseData
     */
    constructor() { 
        
        RegenerateDomainToken200ResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RegenerateDomainToken200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegenerateDomainToken200ResponseData} obj Optional instance to populate.
     * @return {module:model/RegenerateDomainToken200ResponseData} The populated <code>RegenerateDomainToken200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegenerateDomainToken200ResponseData();

            if (data.hasOwnProperty('domain_token')) {
                obj['domain_token'] = ApiClient.convertToType(data['domain_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RegenerateDomainToken200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RegenerateDomainToken200ResponseData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['domain_token'] && !(typeof data['domain_token'] === 'string' || data['domain_token'] instanceof String)) {
            throw new Error("Expected the field `domain_token` to be a primitive type in the JSON string but got " + data['domain_token']);
        }

        return true;
    }


}



/**
 * @member {String} domain_token
 */
RegenerateDomainToken200ResponseData.prototype['domain_token'] = undefined;






export default RegenerateDomainToken200ResponseData;

