/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegisterANewDomainRequest model module.
 * @module model/RegisterANewDomainRequest
 * @version 1.0.0
 */
class RegisterANewDomainRequest {
    /**
     * Constructs a new <code>RegisterANewDomainRequest</code>.
     * @alias module:model/RegisterANewDomainRequest
     * @param domain {String} The domain to register (e.g., \"casino.example.com\").
     */
    constructor(domain) { 
        
        RegisterANewDomainRequest.initialize(this, domain);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, domain) { 
        obj['domain'] = domain;
    }

    /**
     * Constructs a <code>RegisterANewDomainRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisterANewDomainRequest} obj Optional instance to populate.
     * @return {module:model/RegisterANewDomainRequest} The populated <code>RegisterANewDomainRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterANewDomainRequest();

            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('allowed_widgets')) {
                obj['allowed_widgets'] = ApiClient.convertToType(data['allowed_widgets'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RegisterANewDomainRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RegisterANewDomainRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RegisterANewDomainRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['domain'] && !(typeof data['domain'] === 'string' || data['domain'] instanceof String)) {
            throw new Error("Expected the field `domain` to be a primitive type in the JSON string but got " + data['domain']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['allowed_widgets'])) {
            throw new Error("Expected the field `allowed_widgets` to be an array in the JSON data but got " + data['allowed_widgets']);
        }

        return true;
    }


}

RegisterANewDomainRequest.RequiredProperties = ["domain"];

/**
 * The domain to register (e.g., \"casino.example.com\").
 * @member {String} domain
 */
RegisterANewDomainRequest.prototype['domain'] = undefined;

/**
 * optional List of allowed widget types. Default: [\"jackpot\"].
 * @member {Array.<String>} allowed_widgets
 */
RegisterANewDomainRequest.prototype['allowed_widgets'] = undefined;






export default RegisterANewDomainRequest;

