/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RemoveGamesFromAJackpotPoolTypeRequest model module.
 * @module model/RemoveGamesFromAJackpotPoolTypeRequest
 * @version 1.0.0
 */
class RemoveGamesFromAJackpotPoolTypeRequest {
    /**
     * Constructs a new <code>RemoveGamesFromAJackpotPoolTypeRequest</code>.
     * @alias module:model/RemoveGamesFromAJackpotPoolTypeRequest
     * @param poolType {module:model/RemoveGamesFromAJackpotPoolTypeRequest.PoolTypeEnum} 
     */
    constructor(poolType) { 
        
        RemoveGamesFromAJackpotPoolTypeRequest.initialize(this, poolType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, poolType) { 
        obj['pool_type'] = poolType;
    }

    /**
     * Constructs a <code>RemoveGamesFromAJackpotPoolTypeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemoveGamesFromAJackpotPoolTypeRequest} obj Optional instance to populate.
     * @return {module:model/RemoveGamesFromAJackpotPoolTypeRequest} The populated <code>RemoveGamesFromAJackpotPoolTypeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemoveGamesFromAJackpotPoolTypeRequest();

            if (data.hasOwnProperty('pool_type')) {
                obj['pool_type'] = ApiClient.convertToType(data['pool_type'], 'String');
            }
            if (data.hasOwnProperty('game_ids')) {
                obj['game_ids'] = ApiClient.convertToType(data['game_ids'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RemoveGamesFromAJackpotPoolTypeRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RemoveGamesFromAJackpotPoolTypeRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RemoveGamesFromAJackpotPoolTypeRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['pool_type'] && !(typeof data['pool_type'] === 'string' || data['pool_type'] instanceof String)) {
            throw new Error("Expected the field `pool_type` to be a primitive type in the JSON string but got " + data['pool_type']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['game_ids'])) {
            throw new Error("Expected the field `game_ids` to be an array in the JSON data but got " + data['game_ids']);
        }

        return true;
    }


}

RemoveGamesFromAJackpotPoolTypeRequest.RequiredProperties = ["pool_type"];

/**
 * 
 * @member {module:model/RemoveGamesFromAJackpotPoolTypeRequest.PoolTypeEnum} pool_type
 */
RemoveGamesFromAJackpotPoolTypeRequest.prototype['pool_type'] = undefined;

/**
 * 
 * @member {Array.<Number>} game_ids
 */
RemoveGamesFromAJackpotPoolTypeRequest.prototype['game_ids'] = undefined;





/**
 * Allowed values for the <code>pool_type</code> property.
 * @enum {String}
 * @readonly
 */
RemoveGamesFromAJackpotPoolTypeRequest['PoolTypeEnum'] = {

    /**
     * value: "daily"
     * @const
     */
    "daily": "daily",

    /**
     * value: "weekly"
     * @const
     */
    "weekly": "weekly",

    /**
     * value: "monthly"
     * @const
     */
    "monthly": "monthly",

    /**
     * value: "grand_prize"
     * @const
     */
    "grand_prize": "grand_prize"
};



export default RemoveGamesFromAJackpotPoolTypeRequest;

