/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateDomainSettings200ResponseData model module.
 * @module model/UpdateDomainSettings200ResponseData
 * @version 1.0.0
 */
class UpdateDomainSettings200ResponseData {
    /**
     * Constructs a new <code>UpdateDomainSettings200ResponseData</code>.
     * @alias module:model/UpdateDomainSettings200ResponseData
     */
    constructor() { 
        
        UpdateDomainSettings200ResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateDomainSettings200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateDomainSettings200ResponseData} obj Optional instance to populate.
     * @return {module:model/UpdateDomainSettings200ResponseData} The populated <code>UpdateDomainSettings200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateDomainSettings200ResponseData();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
            if (data.hasOwnProperty('allowed_widgets')) {
                obj['allowed_widgets'] = ApiClient.convertToType(data['allowed_widgets'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateDomainSettings200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateDomainSettings200ResponseData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['domain'] && !(typeof data['domain'] === 'string' || data['domain'] instanceof String)) {
            throw new Error("Expected the field `domain` to be a primitive type in the JSON string but got " + data['domain']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['allowed_widgets'])) {
            throw new Error("Expected the field `allowed_widgets` to be an array in the JSON data but got " + data['allowed_widgets']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
UpdateDomainSettings200ResponseData.prototype['id'] = undefined;

/**
 * @member {String} domain
 */
UpdateDomainSettings200ResponseData.prototype['domain'] = undefined;

/**
 * @member {Boolean} is_active
 */
UpdateDomainSettings200ResponseData.prototype['is_active'] = undefined;

/**
 * @member {Array.<String>} allowed_widgets
 */
UpdateDomainSettings200ResponseData.prototype['allowed_widgets'] = undefined;






export default UpdateDomainSettings200ResponseData;

