/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateAPromotionRequest model module.
 * @module model/UpdateAPromotionRequest
 * @version 1.0.0
 */
class UpdateAPromotionRequest {
    /**
     * Constructs a new <code>UpdateAPromotionRequest</code>.
     * @alias module:model/UpdateAPromotionRequest
     */
    constructor() { 
        
        UpdateAPromotionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateAPromotionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateAPromotionRequest} obj Optional instance to populate.
     * @return {module:model/UpdateAPromotionRequest} The populated <code>UpdateAPromotionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateAPromotionRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
            if (data.hasOwnProperty('terms_and_conditions')) {
                obj['terms_and_conditions'] = ApiClient.convertToType(data['terms_and_conditions'], 'String');
            }
            if (data.hasOwnProperty('ends_at')) {
                obj['ends_at'] = ApiClient.convertToType(data['ends_at'], 'String');
            }
            if (data.hasOwnProperty('prize_distribution')) {
                obj['prize_distribution'] = ApiClient.convertToType(data['prize_distribution'], Object);
            }
            if (data.hasOwnProperty('total_prize_pool')) {
                obj['total_prize_pool'] = ApiClient.convertToType(data['total_prize_pool'], 'Number');
            }
            if (data.hasOwnProperty('winner_count')) {
                obj['winner_count'] = ApiClient.convertToType(data['winner_count'], 'Number');
            }
            if (data.hasOwnProperty('entry_config')) {
                obj['entry_config'] = ApiClient.convertToType(data['entry_config'], Object);
            }
            if (data.hasOwnProperty('game_filter_enabled')) {
                obj['game_filter_enabled'] = ApiClient.convertToType(data['game_filter_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('producer_filter_enabled')) {
                obj['producer_filter_enabled'] = ApiClient.convertToType(data['producer_filter_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('webhook_enabled')) {
                obj['webhook_enabled'] = ApiClient.convertToType(data['webhook_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
            if (data.hasOwnProperty('is_featured')) {
                obj['is_featured'] = ApiClient.convertToType(data['is_featured'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateAPromotionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateAPromotionRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['image_url'] && !(typeof data['image_url'] === 'string' || data['image_url'] instanceof String)) {
            throw new Error("Expected the field `image_url` to be a primitive type in the JSON string but got " + data['image_url']);
        }
        // ensure the json data is a string
        if (data['terms_and_conditions'] && !(typeof data['terms_and_conditions'] === 'string' || data['terms_and_conditions'] instanceof String)) {
            throw new Error("Expected the field `terms_and_conditions` to be a primitive type in the JSON string but got " + data['terms_and_conditions']);
        }
        // ensure the json data is a string
        if (data['ends_at'] && !(typeof data['ends_at'] === 'string' || data['ends_at'] instanceof String)) {
            throw new Error("Expected the field `ends_at` to be a primitive type in the JSON string but got " + data['ends_at']);
        }

        return true;
    }


}



/**
 * Must not be greater than 255 characters.
 * @member {String} name
 */
UpdateAPromotionRequest.prototype['name'] = undefined;

/**
 * 
 * @member {String} description
 */
UpdateAPromotionRequest.prototype['description'] = undefined;

/**
 * Must be a valid URL.
 * @member {String} image_url
 */
UpdateAPromotionRequest.prototype['image_url'] = undefined;

/**
 * 
 * @member {String} terms_and_conditions
 */
UpdateAPromotionRequest.prototype['terms_and_conditions'] = undefined;

/**
 * Must be a valid date.
 * @member {String} ends_at
 */
UpdateAPromotionRequest.prototype['ends_at'] = undefined;

/**
 * 
 * @member {Object} prize_distribution
 */
UpdateAPromotionRequest.prototype['prize_distribution'] = undefined;

/**
 * Must be at least 0.
 * @member {Number} total_prize_pool
 */
UpdateAPromotionRequest.prototype['total_prize_pool'] = undefined;

/**
 * Must be at least 1.
 * @member {Number} winner_count
 */
UpdateAPromotionRequest.prototype['winner_count'] = undefined;

/**
 * 
 * @member {Object} entry_config
 */
UpdateAPromotionRequest.prototype['entry_config'] = undefined;

/**
 * 
 * @member {Boolean} game_filter_enabled
 */
UpdateAPromotionRequest.prototype['game_filter_enabled'] = undefined;

/**
 * 
 * @member {Boolean} producer_filter_enabled
 */
UpdateAPromotionRequest.prototype['producer_filter_enabled'] = undefined;

/**
 * 
 * @member {Boolean} webhook_enabled
 */
UpdateAPromotionRequest.prototype['webhook_enabled'] = undefined;

/**
 * 
 * @member {Boolean} is_active
 */
UpdateAPromotionRequest.prototype['is_active'] = undefined;

/**
 * 
 * @member {Boolean} is_featured
 */
UpdateAPromotionRequest.prototype['is_featured'] = undefined;






export default UpdateAPromotionRequest;

