/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateAnExternalGameRequest model module.
 * @module model/UpdateAnExternalGameRequest
 * @version 1.0.0
 */
class UpdateAnExternalGameRequest {
    /**
     * Constructs a new <code>UpdateAnExternalGameRequest</code>.
     * @alias module:model/UpdateAnExternalGameRequest
     */
    constructor() { 
        
        UpdateAnExternalGameRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateAnExternalGameRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateAnExternalGameRequest} obj Optional instance to populate.
     * @return {module:model/UpdateAnExternalGameRequest} The populated <code>UpdateAnExternalGameRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateAnExternalGameRequest();

            if (data.hasOwnProperty('external_game_id')) {
                obj['external_game_id'] = ApiClient.convertToType(data['external_game_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('producer_name')) {
                obj['producer_name'] = ApiClient.convertToType(data['producer_name'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateAnExternalGameRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateAnExternalGameRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['external_game_id'] && !(typeof data['external_game_id'] === 'string' || data['external_game_id'] instanceof String)) {
            throw new Error("Expected the field `external_game_id` to be a primitive type in the JSON string but got " + data['external_game_id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['producer_name'] && !(typeof data['producer_name'] === 'string' || data['producer_name'] instanceof String)) {
            throw new Error("Expected the field `producer_name` to be a primitive type in the JSON string but got " + data['producer_name']);
        }
        // ensure the json data is a string
        if (data['image_url'] && !(typeof data['image_url'] === 'string' || data['image_url'] instanceof String)) {
            throw new Error("Expected the field `image_url` to be a primitive type in the JSON string but got " + data['image_url']);
        }

        return true;
    }


}



/**
 * Must not be greater than 100 characters.
 * @member {String} external_game_id
 */
UpdateAnExternalGameRequest.prototype['external_game_id'] = undefined;

/**
 * Must not be greater than 255 characters.
 * @member {String} name
 */
UpdateAnExternalGameRequest.prototype['name'] = undefined;

/**
 * Must not be greater than 255 characters.
 * @member {String} producer_name
 */
UpdateAnExternalGameRequest.prototype['producer_name'] = undefined;

/**
 * Must be a valid URL. Must not be greater than 500 characters.
 * @member {String} image_url
 */
UpdateAnExternalGameRequest.prototype['image_url'] = undefined;

/**
 * 
 * @member {Object} metadata
 */
UpdateAnExternalGameRequest.prototype['metadata'] = undefined;

/**
 * 
 * @member {Boolean} is_active
 */
UpdateAnExternalGameRequest.prototype['is_active'] = undefined;






export default UpdateAnExternalGameRequest;

