/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AddAContributionToAJackpotPoolRequest from '../model/AddAContributionToAJackpotPoolRequest';
import AddGamesToAJackpotPoolTypeRequest from '../model/AddGamesToAJackpotPoolTypeRequest';
import BulkCreateExternalGamesFromJSONArrayRequest from '../model/BulkCreateExternalGamesFromJSONArrayRequest';
import BulkDeleteExternalGamesByIDsRequest from '../model/BulkDeleteExternalGamesByIDsRequest';
import ConfigureJackpotSettingsForTheOperatorRequest from '../model/ConfigureJackpotSettingsForTheOperatorRequest';
import ConfigureLiveModeSettingsForAPoolRequest from '../model/ConfigureLiveModeSettingsForAPoolRequest';
import CreateANewPromotionRequest from '../model/CreateANewPromotionRequest';
import CreateASingleExternalGameRequest from '../model/CreateASingleExternalGameRequest';
import CreateATargetedPlayerConfigurationRequest from '../model/CreateATargetedPlayerConfigurationRequest';
import GetApiV1Producers401Response from '../model/GetApiV1Producers401Response';
import GetApiV1TransactionExportsExportIdDownload500Response from '../model/GetApiV1TransactionExportsExportIdDownload500Response';
import GetGamesForAPoolTypeOrAllPoolTypesRequest from '../model/GetGamesForAPoolTypeOrAllPoolTypesRequest';
import GetPlayerContributionHistoryRequest from '../model/GetPlayerContributionHistoryRequest';
import ImportExternalGamesFromJSONPasteRequest from '../model/ImportExternalGamesFromJSONPasteRequest';
import ListExternalGamesForOperatorRequest from '../model/ListExternalGamesForOperatorRequest';
import ListOperatorsJackpotPoolsRequest from '../model/ListOperatorsJackpotPoolsRequest';
import ListTargetedPlayersForOperatorRequest from '../model/ListTargetedPlayersForOperatorRequest';
import ManageGamesForAPromotionRequest from '../model/ManageGamesForAPromotionRequest';
import PostApiV1GameTransactionsExportRequest from '../model/PostApiV1GameTransactionsExportRequest';
import RemoveGamesFromAJackpotPoolTypeRequest from '../model/RemoveGamesFromAJackpotPoolTypeRequest';
import SetGrandPrizeExpirationDateRequest from '../model/SetGrandPrizeExpirationDateRequest';
import UpdateAPromotionRequest from '../model/UpdateAPromotionRequest';
import UpdateAnExternalGameRequest from '../model/UpdateAnExternalGameRequest';

/**
* Endpoints service.
* @module api/EndpointsApi
* @version 1.0.0
*/
export default class EndpointsApi {

    /**
    * Constructs a new EndpointsApi. 
    * @alias module:api/EndpointsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Add a contribution to a jackpot pool
     * 
     * @param {module:model/AddAContributionToAJackpotPoolRequest} addAContributionToAJackpotPoolRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    addAContributionToAJackpotPoolWithHttpInfo(addAContributionToAJackpotPoolRequest) {
      let postBody = addAContributionToAJackpotPoolRequest;
      // verify the required parameter 'addAContributionToAJackpotPoolRequest' is set
      if (addAContributionToAJackpotPoolRequest === undefined || addAContributionToAJackpotPoolRequest === null) {
        throw new Error("Missing the required parameter 'addAContributionToAJackpotPoolRequest' when calling addAContributionToAJackpotPool");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/contribute', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Add a contribution to a jackpot pool
     * 
     * @param {module:model/AddAContributionToAJackpotPoolRequest} addAContributionToAJackpotPoolRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    addAContributionToAJackpotPool(addAContributionToAJackpotPoolRequest) {
      return this.addAContributionToAJackpotPoolWithHttpInfo(addAContributionToAJackpotPoolRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Add games to a jackpot pool type
     * 
     * @param {module:model/AddGamesToAJackpotPoolTypeRequest} addGamesToAJackpotPoolTypeRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    addGamesToAJackpotPoolTypeWithHttpInfo(addGamesToAJackpotPoolTypeRequest) {
      let postBody = addGamesToAJackpotPoolTypeRequest;
      // verify the required parameter 'addGamesToAJackpotPoolTypeRequest' is set
      if (addGamesToAJackpotPoolTypeRequest === undefined || addGamesToAJackpotPoolTypeRequest === null) {
        throw new Error("Missing the required parameter 'addGamesToAJackpotPoolTypeRequest' when calling addGamesToAJackpotPoolType");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/games', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Add games to a jackpot pool type
     * 
     * @param {module:model/AddGamesToAJackpotPoolTypeRequest} addGamesToAJackpotPoolTypeRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    addGamesToAJackpotPoolType(addGamesToAJackpotPoolTypeRequest) {
      return this.addGamesToAJackpotPoolTypeWithHttpInfo(addGamesToAJackpotPoolTypeRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Bulk create external games from JSON array
     * 
     * @param {module:model/BulkCreateExternalGamesFromJSONArrayRequest} bulkCreateExternalGamesFromJSONArrayRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    bulkCreateExternalGamesFromJSONArrayWithHttpInfo(bulkCreateExternalGamesFromJSONArrayRequest) {
      let postBody = bulkCreateExternalGamesFromJSONArrayRequest;
      // verify the required parameter 'bulkCreateExternalGamesFromJSONArrayRequest' is set
      if (bulkCreateExternalGamesFromJSONArrayRequest === undefined || bulkCreateExternalGamesFromJSONArrayRequest === null) {
        throw new Error("Missing the required parameter 'bulkCreateExternalGamesFromJSONArrayRequest' when calling bulkCreateExternalGamesFromJSONArray");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/external-games/bulk', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Bulk create external games from JSON array
     * 
     * @param {module:model/BulkCreateExternalGamesFromJSONArrayRequest} bulkCreateExternalGamesFromJSONArrayRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    bulkCreateExternalGamesFromJSONArray(bulkCreateExternalGamesFromJSONArrayRequest) {
      return this.bulkCreateExternalGamesFromJSONArrayWithHttpInfo(bulkCreateExternalGamesFromJSONArrayRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Bulk delete external games by IDs
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/BulkDeleteExternalGamesByIDsRequest} [bulkDeleteExternalGamesByIDsRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    bulkDeleteExternalGamesByIDsWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['bulkDeleteExternalGamesByIDsRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/external-games/bulk', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Bulk delete external games by IDs
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/BulkDeleteExternalGamesByIDsRequest} opts.bulkDeleteExternalGamesByIDsRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    bulkDeleteExternalGamesByIDs(opts) {
      return this.bulkDeleteExternalGamesByIDsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Configure jackpot settings for the operator
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/ConfigureJackpotSettingsForTheOperatorRequest} [configureJackpotSettingsForTheOperatorRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    configureJackpotSettingsForTheOperatorWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['configureJackpotSettingsForTheOperatorRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/configure', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Configure jackpot settings for the operator
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/ConfigureJackpotSettingsForTheOperatorRequest} opts.configureJackpotSettingsForTheOperatorRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    configureJackpotSettingsForTheOperator(opts) {
      return this.configureJackpotSettingsForTheOperatorWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Configure live mode settings for a pool
     * 
     * @param {String} poolId 
     * @param {module:model/ConfigureLiveModeSettingsForAPoolRequest} configureLiveModeSettingsForAPoolRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    configureLiveModeSettingsForAPoolWithHttpInfo(poolId, configureLiveModeSettingsForAPoolRequest) {
      let postBody = configureLiveModeSettingsForAPoolRequest;
      // verify the required parameter 'poolId' is set
      if (poolId === undefined || poolId === null) {
        throw new Error("Missing the required parameter 'poolId' when calling configureLiveModeSettingsForAPool");
      }
      // verify the required parameter 'configureLiveModeSettingsForAPoolRequest' is set
      if (configureLiveModeSettingsForAPoolRequest === undefined || configureLiveModeSettingsForAPoolRequest === null) {
        throw new Error("Missing the required parameter 'configureLiveModeSettingsForAPoolRequest' when calling configureLiveModeSettingsForAPool");
      }

      let pathParams = {
        'poolId': poolId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/pools/{poolId}/live-mode', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Configure live mode settings for a pool
     * 
     * @param {String} poolId 
     * @param {module:model/ConfigureLiveModeSettingsForAPoolRequest} configureLiveModeSettingsForAPoolRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    configureLiveModeSettingsForAPool(poolId, configureLiveModeSettingsForAPoolRequest) {
      return this.configureLiveModeSettingsForAPoolWithHttpInfo(poolId, configureLiveModeSettingsForAPoolRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a new promotion
     * 
     * @param {module:model/CreateANewPromotionRequest} createANewPromotionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    createANewPromotionWithHttpInfo(createANewPromotionRequest) {
      let postBody = createANewPromotionRequest;
      // verify the required parameter 'createANewPromotionRequest' is set
      if (createANewPromotionRequest === undefined || createANewPromotionRequest === null) {
        throw new Error("Missing the required parameter 'createANewPromotionRequest' when calling createANewPromotion");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/promotions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a new promotion
     * 
     * @param {module:model/CreateANewPromotionRequest} createANewPromotionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    createANewPromotion(createANewPromotionRequest) {
      return this.createANewPromotionWithHttpInfo(createANewPromotionRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a single external game
     * 
     * @param {module:model/CreateASingleExternalGameRequest} createASingleExternalGameRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    createASingleExternalGameWithHttpInfo(createASingleExternalGameRequest) {
      let postBody = createASingleExternalGameRequest;
      // verify the required parameter 'createASingleExternalGameRequest' is set
      if (createASingleExternalGameRequest === undefined || createASingleExternalGameRequest === null) {
        throw new Error("Missing the required parameter 'createASingleExternalGameRequest' when calling createASingleExternalGame");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/external-games', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a single external game
     * 
     * @param {module:model/CreateASingleExternalGameRequest} createASingleExternalGameRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    createASingleExternalGame(createASingleExternalGameRequest) {
      return this.createASingleExternalGameWithHttpInfo(createASingleExternalGameRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a targeted player configuration
     * 
     * @param {module:model/CreateATargetedPlayerConfigurationRequest} createATargetedPlayerConfigurationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    createATargetedPlayerConfigurationWithHttpInfo(createATargetedPlayerConfigurationRequest) {
      let postBody = createATargetedPlayerConfigurationRequest;
      // verify the required parameter 'createATargetedPlayerConfigurationRequest' is set
      if (createATargetedPlayerConfigurationRequest === undefined || createATargetedPlayerConfigurationRequest === null) {
        throw new Error("Missing the required parameter 'createATargetedPlayerConfigurationRequest' when calling createATargetedPlayerConfiguration");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/targeted-players', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a targeted player configuration
     * 
     * @param {module:model/CreateATargetedPlayerConfigurationRequest} createATargetedPlayerConfigurationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    createATargetedPlayerConfiguration(createATargetedPlayerConfigurationRequest) {
      return this.createATargetedPlayerConfigurationWithHttpInfo(createATargetedPlayerConfigurationRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Deactivate a targeted player configuration
     * 
     * @param {String} targetedPlayerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deactivateATargetedPlayerConfigurationWithHttpInfo(targetedPlayerId) {
      let postBody = null;
      // verify the required parameter 'targetedPlayerId' is set
      if (targetedPlayerId === undefined || targetedPlayerId === null) {
        throw new Error("Missing the required parameter 'targetedPlayerId' when calling deactivateATargetedPlayerConfiguration");
      }

      let pathParams = {
        'targetedPlayerId': targetedPlayerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/targeted-players/{targetedPlayerId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Deactivate a targeted player configuration
     * 
     * @param {String} targetedPlayerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deactivateATargetedPlayerConfiguration(targetedPlayerId) {
      return this.deactivateATargetedPlayerConfigurationWithHttpInfo(targetedPlayerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteAPromotionWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteAPromotion");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/promotions/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete a promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteAPromotion(id) {
      return this.deleteAPromotionWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete an external game
     * 
     * @param {String} id The ID of the external game.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteAnExternalGameWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteAnExternalGame");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/external-games/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete an external game
     * 
     * @param {String} id The ID of the external game.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteAnExternalGame(id) {
      return this.deleteAnExternalGameWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a single external game
     * 
     * @param {String} id The ID of the external game.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getASingleExternalGameWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getASingleExternalGame");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/external-games/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a single external game
     * 
     * @param {String} id The ID of the external game.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getASingleExternalGame(id) {
      return this.getASingleExternalGameWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a specific promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getASpecificPromotionWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getASpecificPromotion");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/promotions/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a specific promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getASpecificPromotion(id) {
      return this.getASpecificPromotionWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * 
     * 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getApiV1ProducersWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/producers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * 
     * 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getApiV1Producers() {
      return this.getApiV1ProducersWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * 
     * 
     * @param {String} id The ID of the producer.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getApiV1ProducersIdWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getApiV1ProducersId");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/producers/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * 
     * 
     * @param {String} id The ID of the producer.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getApiV1ProducersId(id) {
      return this.getApiV1ProducersIdWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * 
     * 
     * @param {Number} exportId The ID of the export.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getApiV1TransactionExportsExportIdDownloadWithHttpInfo(exportId) {
      let postBody = null;
      // verify the required parameter 'exportId' is set
      if (exportId === undefined || exportId === null) {
        throw new Error("Missing the required parameter 'exportId' when calling getApiV1TransactionExportsExportIdDownload");
      }

      let pathParams = {
        'export_id': exportId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/transaction-exports/{export_id}/download', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * 
     * 
     * @param {Number} exportId The ID of the export.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getApiV1TransactionExportsExportIdDownload(exportId) {
      return this.getApiV1TransactionExportsExportIdDownloadWithHttpInfo(exportId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get current configuration with games
     * 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getCurrentConfigurationWithGamesWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/configuration', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get current configuration with games
     * 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getCurrentConfigurationWithGames() {
      return this.getCurrentConfigurationWithGamesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get games for a pool type or all pool types
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/GetGamesForAPoolTypeOrAllPoolTypesRequest} [getGamesForAPoolTypeOrAllPoolTypesRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getGamesForAPoolTypeOrAllPoolTypesWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['getGamesForAPoolTypeOrAllPoolTypesRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/games', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get games for a pool type or all pool types
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/GetGamesForAPoolTypeOrAllPoolTypesRequest} opts.getGamesForAPoolTypeOrAllPoolTypesRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getGamesForAPoolTypeOrAllPoolTypes(opts) {
      return this.getGamesForAPoolTypeOrAllPoolTypesWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get leaderboard for a promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getLeaderboardForAPromotionWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getLeaderboardForAPromotion");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/promotions/{id}/leaderboard', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get leaderboard for a promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getLeaderboardForAPromotion(id) {
      return this.getLeaderboardForAPromotionWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get player contribution history
     * 
     * @param {module:model/GetPlayerContributionHistoryRequest} getPlayerContributionHistoryRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getPlayerContributionHistoryWithHttpInfo(getPlayerContributionHistoryRequest) {
      let postBody = getPlayerContributionHistoryRequest;
      // verify the required parameter 'getPlayerContributionHistoryRequest' is set
      if (getPlayerContributionHistoryRequest === undefined || getPlayerContributionHistoryRequest === null) {
        throw new Error("Missing the required parameter 'getPlayerContributionHistoryRequest' when calling getPlayerContributionHistory");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/contributions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get player contribution history
     * 
     * @param {module:model/GetPlayerContributionHistoryRequest} getPlayerContributionHistoryRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getPlayerContributionHistory(getPlayerContributionHistoryRequest) {
      return this.getPlayerContributionHistoryWithHttpInfo(getPlayerContributionHistoryRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get pool details
     * 
     * @param {String} poolId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getPoolDetailsWithHttpInfo(poolId) {
      let postBody = null;
      // verify the required parameter 'poolId' is set
      if (poolId === undefined || poolId === null) {
        throw new Error("Missing the required parameter 'poolId' when calling getPoolDetails");
      }

      let pathParams = {
        'poolId': poolId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/pools/{poolId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get pool details
     * 
     * @param {String} poolId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getPoolDetails(poolId) {
      return this.getPoolDetailsWithHttpInfo(poolId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get pool winners
     * 
     * @param {String} poolId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getPoolWinnersWithHttpInfo(poolId) {
      let postBody = null;
      // verify the required parameter 'poolId' is set
      if (poolId === undefined || poolId === null) {
        throw new Error("Missing the required parameter 'poolId' when calling getPoolWinners");
      }

      let pathParams = {
        'poolId': poolId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/pools/{poolId}/winners', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get pool winners
     * 
     * @param {String} poolId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getPoolWinners(poolId) {
      return this.getPoolWinnersWithHttpInfo(poolId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get targeted player details
     * 
     * @param {String} targetedPlayerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getTargetedPlayerDetailsWithHttpInfo(targetedPlayerId) {
      let postBody = null;
      // verify the required parameter 'targetedPlayerId' is set
      if (targetedPlayerId === undefined || targetedPlayerId === null) {
        throw new Error("Missing the required parameter 'targetedPlayerId' when calling getTargetedPlayerDetails");
      }

      let pathParams = {
        'targetedPlayerId': targetedPlayerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/targeted-players/{targetedPlayerId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get targeted player details
     * 
     * @param {String} targetedPlayerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getTargetedPlayerDetails(targetedPlayerId) {
      return this.getTargetedPlayerDetailsWithHttpInfo(targetedPlayerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get unique producer names for filtering
     * 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getUniqueProducerNamesForFilteringWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/external-games/producers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get unique producer names for filtering
     * 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getUniqueProducerNamesForFiltering() {
      return this.getUniqueProducerNamesForFilteringWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get winners for a promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getWinnersForAPromotionWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getWinnersForAPromotion");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/promotions/{id}/winners', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get winners for a promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getWinnersForAPromotion(id) {
      return this.getWinnersForAPromotionWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Import external games from CSV file
     * 
     * @param {File} file Must be a file. Must not be greater than 10240 kilobytes.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    importExternalGamesFromCSVFileWithHttpInfo(file) {
      let postBody = null;
      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling importExternalGamesFromCSVFile");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'file': file
      };

      let authNames = ['default'];
      let contentTypes = ['multipart/form-data'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/external-games/import/csv', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Import external games from CSV file
     * 
     * @param {File} file Must be a file. Must not be greater than 10240 kilobytes.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    importExternalGamesFromCSVFile(file) {
      return this.importExternalGamesFromCSVFileWithHttpInfo(file)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Import external games from JSON paste
     * 
     * @param {module:model/ImportExternalGamesFromJSONPasteRequest} importExternalGamesFromJSONPasteRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    importExternalGamesFromJSONPasteWithHttpInfo(importExternalGamesFromJSONPasteRequest) {
      let postBody = importExternalGamesFromJSONPasteRequest;
      // verify the required parameter 'importExternalGamesFromJSONPasteRequest' is set
      if (importExternalGamesFromJSONPasteRequest === undefined || importExternalGamesFromJSONPasteRequest === null) {
        throw new Error("Missing the required parameter 'importExternalGamesFromJSONPasteRequest' when calling importExternalGamesFromJSONPaste");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/external-games/import/json', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Import external games from JSON paste
     * 
     * @param {module:model/ImportExternalGamesFromJSONPasteRequest} importExternalGamesFromJSONPasteRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    importExternalGamesFromJSONPaste(importExternalGamesFromJSONPasteRequest) {
      return this.importExternalGamesFromJSONPasteWithHttpInfo(importExternalGamesFromJSONPasteRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List external games for operator
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/ListExternalGamesForOperatorRequest} [listExternalGamesForOperatorRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    listExternalGamesForOperatorWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['listExternalGamesForOperatorRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/external-games', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List external games for operator
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/ListExternalGamesForOperatorRequest} opts.listExternalGamesForOperatorRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    listExternalGamesForOperator(opts) {
      return this.listExternalGamesForOperatorWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List operator's jackpot pools
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/ListOperatorsJackpotPoolsRequest} [listOperatorsJackpotPoolsRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    listOperatorsJackpotPoolsWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['listOperatorsJackpotPoolsRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/pools', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List operator's jackpot pools
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/ListOperatorsJackpotPoolsRequest} opts.listOperatorsJackpotPoolsRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    listOperatorsJackpotPools(opts) {
      return this.listOperatorsJackpotPoolsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List promotions for the operator
     * 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    listPromotionsForTheOperatorWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/promotions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List promotions for the operator
     * 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    listPromotionsForTheOperator() {
      return this.listPromotionsForTheOperatorWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List targeted players for operator
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/ListTargetedPlayersForOperatorRequest} [listTargetedPlayersForOperatorRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    listTargetedPlayersForOperatorWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['listTargetedPlayersForOperatorRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/targeted-players', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List targeted players for operator
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/ListTargetedPlayersForOperatorRequest} opts.listTargetedPlayersForOperatorRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    listTargetedPlayersForOperator(opts) {
      return this.listTargetedPlayersForOperatorWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Manage games for a promotion
     * 
     * @param {String} id The ID of the promotion.
     * @param {Object} opts Optional parameters
     * @param {module:model/ManageGamesForAPromotionRequest} [manageGamesForAPromotionRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    manageGamesForAPromotionWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['manageGamesForAPromotionRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling manageGamesForAPromotion");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/promotions/{id}/games', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Manage games for a promotion
     * 
     * @param {String} id The ID of the promotion.
     * @param {Object} opts Optional parameters
     * @param {module:model/ManageGamesForAPromotionRequest} opts.manageGamesForAPromotionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    manageGamesForAPromotion(id, opts) {
      return this.manageGamesForAPromotionWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Manually distribute prizes for a period
     * 
     * @param {String} id The ID of the promotion.
     * @param {String} periodId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    manuallyDistributePrizesForAPeriodWithHttpInfo(id, periodId) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling manuallyDistributePrizesForAPeriod");
      }
      // verify the required parameter 'periodId' is set
      if (periodId === undefined || periodId === null) {
        throw new Error("Missing the required parameter 'periodId' when calling manuallyDistributePrizesForAPeriod");
      }

      let pathParams = {
        'id': id,
        'periodId': periodId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/promotions/{id}/periods/{periodId}/distribute', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Manually distribute prizes for a period
     * 
     * @param {String} id The ID of the promotion.
     * @param {String} periodId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    manuallyDistributePrizesForAPeriod(id, periodId) {
      return this.manuallyDistributePrizesForAPeriodWithHttpInfo(id, periodId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Manually trigger pool release
     * 
     * @param {String} poolId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    manuallyTriggerPoolReleaseWithHttpInfo(poolId) {
      let postBody = null;
      // verify the required parameter 'poolId' is set
      if (poolId === undefined || poolId === null) {
        throw new Error("Missing the required parameter 'poolId' when calling manuallyTriggerPoolRelease");
      }

      let pathParams = {
        'poolId': poolId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/pools/{poolId}/release', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Manually trigger pool release
     * 
     * @param {String} poolId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    manuallyTriggerPoolRelease(poolId) {
      return this.manuallyTriggerPoolReleaseWithHttpInfo(poolId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Opt-in operator to a platform/network promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    optInOperatorToAPlatformnetworkPromotionWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling optInOperatorToAPlatformnetworkPromotion");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/promotions/{id}/opt-in', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Opt-in operator to a platform/network promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    optInOperatorToAPlatformnetworkPromotion(id) {
      return this.optInOperatorToAPlatformnetworkPromotionWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Opt-out operator from a platform/network promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    optOutOperatorFromAPlatformnetworkPromotionWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling optOutOperatorFromAPlatformnetworkPromotion");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/promotions/{id}/opt-out', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Opt-out operator from a platform/network promotion
     * 
     * @param {String} id The ID of the promotion.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    optOutOperatorFromAPlatformnetworkPromotion(id) {
      return this.optOutOperatorFromAPlatformnetworkPromotionWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * 
     * 
     * @param {module:model/PostApiV1GameTransactionsExportRequest} postApiV1GameTransactionsExportRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    postApiV1GameTransactionsExportWithHttpInfo(postApiV1GameTransactionsExportRequest) {
      let postBody = postApiV1GameTransactionsExportRequest;
      // verify the required parameter 'postApiV1GameTransactionsExportRequest' is set
      if (postApiV1GameTransactionsExportRequest === undefined || postApiV1GameTransactionsExportRequest === null) {
        throw new Error("Missing the required parameter 'postApiV1GameTransactionsExportRequest' when calling postApiV1GameTransactionsExport");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/game-transactions/export', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * 
     * 
     * @param {module:model/PostApiV1GameTransactionsExportRequest} postApiV1GameTransactionsExportRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    postApiV1GameTransactionsExport(postApiV1GameTransactionsExportRequest) {
      return this.postApiV1GameTransactionsExportWithHttpInfo(postApiV1GameTransactionsExportRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Remove games from a jackpot pool type
     * 
     * @param {module:model/RemoveGamesFromAJackpotPoolTypeRequest} removeGamesFromAJackpotPoolTypeRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    removeGamesFromAJackpotPoolTypeWithHttpInfo(removeGamesFromAJackpotPoolTypeRequest) {
      let postBody = removeGamesFromAJackpotPoolTypeRequest;
      // verify the required parameter 'removeGamesFromAJackpotPoolTypeRequest' is set
      if (removeGamesFromAJackpotPoolTypeRequest === undefined || removeGamesFromAJackpotPoolTypeRequest === null) {
        throw new Error("Missing the required parameter 'removeGamesFromAJackpotPoolTypeRequest' when calling removeGamesFromAJackpotPoolType");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/games', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Remove games from a jackpot pool type
     * 
     * @param {module:model/RemoveGamesFromAJackpotPoolTypeRequest} removeGamesFromAJackpotPoolTypeRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    removeGamesFromAJackpotPoolType(removeGamesFromAJackpotPoolTypeRequest) {
      return this.removeGamesFromAJackpotPoolTypeWithHttpInfo(removeGamesFromAJackpotPoolTypeRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Set grand prize expiration date
     * 
     * @param {String} poolId 
     * @param {module:model/SetGrandPrizeExpirationDateRequest} setGrandPrizeExpirationDateRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    setGrandPrizeExpirationDateWithHttpInfo(poolId, setGrandPrizeExpirationDateRequest) {
      let postBody = setGrandPrizeExpirationDateRequest;
      // verify the required parameter 'poolId' is set
      if (poolId === undefined || poolId === null) {
        throw new Error("Missing the required parameter 'poolId' when calling setGrandPrizeExpirationDate");
      }
      // verify the required parameter 'setGrandPrizeExpirationDateRequest' is set
      if (setGrandPrizeExpirationDateRequest === undefined || setGrandPrizeExpirationDateRequest === null) {
        throw new Error("Missing the required parameter 'setGrandPrizeExpirationDateRequest' when calling setGrandPrizeExpirationDate");
      }

      let pathParams = {
        'poolId': poolId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jackpot/pools/{poolId}/expiration', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Set grand prize expiration date
     * 
     * @param {String} poolId 
     * @param {module:model/SetGrandPrizeExpirationDateRequest} setGrandPrizeExpirationDateRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    setGrandPrizeExpirationDate(poolId, setGrandPrizeExpirationDateRequest) {
      return this.setGrandPrizeExpirationDateWithHttpInfo(poolId, setGrandPrizeExpirationDateRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update a promotion
     * 
     * @param {String} id The ID of the promotion.
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateAPromotionRequest} [updateAPromotionRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    updateAPromotionWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['updateAPromotionRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateAPromotion");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/promotions/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update a promotion
     * 
     * @param {String} id The ID of the promotion.
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateAPromotionRequest} opts.updateAPromotionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    updateAPromotion(id, opts) {
      return this.updateAPromotionWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update an external game
     * 
     * @param {String} id The ID of the external game.
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateAnExternalGameRequest} [updateAnExternalGameRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    updateAnExternalGameWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['updateAnExternalGameRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateAnExternalGame");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/external-games/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update an external game
     * 
     * @param {String} id The ID of the external game.
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateAnExternalGameRequest} opts.updateAnExternalGameRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    updateAnExternalGame(id, opts) {
      return this.updateAnExternalGameWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
