/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CancelAStandaloneFreespin401Response from '../model/CancelAStandaloneFreespin401Response';
import GetTransactionDetails404Response from '../model/GetTransactionDetails404Response';
import GetTransactionHistory200Response from '../model/GetTransactionHistory200Response';

/**
* GameTransactions service.
* @module api/GameTransactionsApi
* @version 1.0.0
*/
export default class GameTransactionsApi {

    /**
    * Constructs a new GameTransactionsApi. 
    * @alias module:api/GameTransactionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get transaction details
     * Retrieve detailed information about a specific transaction
     * @param {Number} id The ID of the transaction.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link String} and HTTP response
     */
    getTransactionDetailsWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTransactionDetails");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/v1/game-transactions/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get transaction details
     * Retrieve detailed information about a specific transaction
     * @param {Number} id The ID of the transaction.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link String}
     */
    getTransactionDetails(id) {
      return this.getTransactionDetailsWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get transaction history
     * Retrieve a list of game transactions for the authenticated operator
     * @param {Object} opts Optional parameters
     * @param {String} [playerId] Filter by player ID.
     * @param {Number} [gameId] Filter by game ID.
     * @param {String} [type] Filter by transaction type (bet, win, rollback).
     * @param {String} [fromDate] Filter transactions from date (ISO 8601).
     * @param {String} [toDate] Filter transactions to date (ISO 8601).
     * @param {Number} [limit] Number of results per page. Default: 100.
     * @param {Number} [offset] Number of results to skip. Default: 0.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetTransactionHistory200Response} and HTTP response
     */
    getTransactionHistoryWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'player_id': opts['playerId'],
        'game_id': opts['gameId'],
        'type': opts['type'],
        'from_date': opts['fromDate'],
        'to_date': opts['toDate'],
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetTransactionHistory200Response;
      return this.apiClient.callApi(
        '/api/v1/game-transactions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get transaction history
     * Retrieve a list of game transactions for the authenticated operator
     * @param {Object} opts Optional parameters
     * @param {String} opts.playerId Filter by player ID.
     * @param {Number} opts.gameId Filter by game ID.
     * @param {String} opts.type Filter by transaction type (bet, win, rollback).
     * @param {String} opts.fromDate Filter transactions from date (ISO 8601).
     * @param {String} opts.toDate Filter transactions to date (ISO 8601).
     * @param {Number} opts.limit Number of results per page. Default: 100.
     * @param {Number} opts.offset Number of results to skip. Default: 0.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetTransactionHistory200Response}
     */
    getTransactionHistory(opts) {
      return this.getTransactionHistoryWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
