/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetApiV1Producers401Response from '../model/GetApiV1Producers401Response';
import ListGames200Response from '../model/ListGames200Response';
import ListGamesRequest from '../model/ListGamesRequest';

/**
* Games service.
* @module api/GamesApi
* @version 1.0.0
*/
export default class GamesApi {

    /**
    * Constructs a new GamesApi. 
    * @alias module:api/GamesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * 
     * 
     * @param {String} id The ID of the game.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    getApiV1GamesIdWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getApiV1GamesId");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/games/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * 
     * 
     * @param {String} id The ID of the game.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    getApiV1GamesId(id) {
      return this.getApiV1GamesIdWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List games
     * Get a list of available games for the operator
     * @param {Object} opts Optional parameters
     * @param {String} [search] Search games by name.
     * @param {Number} [producerId] Filter by producer ID.
     * @param {String} [provider] Filter by provider slug.
     * @param {String} [type] Filter by game type.
     * @param {String} [perPage] Number of results per page or \"all\" for all results.
     * @param {module:model/ListGamesRequest} [listGamesRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListGames200Response} and HTTP response
     */
    listGamesWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['listGamesRequest'];

      let pathParams = {
      };
      let queryParams = {
        'search': opts['search'],
        'producer_id': opts['producerId'],
        'provider': opts['provider'],
        'type': opts['type'],
        'per_page': opts['perPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ListGames200Response;
      return this.apiClient.callApi(
        '/api/v1/games', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List games
     * Get a list of available games for the operator
     * @param {Object} opts Optional parameters
     * @param {String} opts.search Search games by name.
     * @param {Number} opts.producerId Filter by producer ID.
     * @param {String} opts.provider Filter by provider slug.
     * @param {String} opts.type Filter by game type.
     * @param {String} opts.perPage Number of results per page or \"all\" for all results.
     * @param {module:model/ListGamesRequest} opts.listGamesRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListGames200Response}
     */
    listGames(opts) {
      return this.listGamesWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
