/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BulkRevokeTokens200Response from '../model/BulkRevokeTokens200Response';
import BulkRevokeTokensRequest from '../model/BulkRevokeTokensRequest';
import GenerateAWidgetToken201Response from '../model/GenerateAWidgetToken201Response';
import GenerateAWidgetToken400Response from '../model/GenerateAWidgetToken400Response';
import GenerateAWidgetToken401Response from '../model/GenerateAWidgetToken401Response';
import GenerateAWidgetTokenRequest from '../model/GenerateAWidgetTokenRequest';
import GetDomainDetails200Response from '../model/GetDomainDetails200Response';
import GetTokenDetails200Response from '../model/GetTokenDetails200Response';
import ListRegisteredDomains200Response from '../model/ListRegisteredDomains200Response';
import ListWidgetTokens200Response from '../model/ListWidgetTokens200Response';
import RegenerateDomainToken200Response from '../model/RegenerateDomainToken200Response';
import RegisterANewDomain201Response from '../model/RegisterANewDomain201Response';
import RegisterANewDomain422Response from '../model/RegisterANewDomain422Response';
import RegisterANewDomainRequest from '../model/RegisterANewDomainRequest';
import RemoveADomain200Response from '../model/RemoveADomain200Response';
import RevokeAToken200Response from '../model/RevokeAToken200Response';
import UpdateDomainSettings200Response from '../model/UpdateDomainSettings200Response';
import UpdateDomainSettingsRequest from '../model/UpdateDomainSettingsRequest';

/**
* WidgetManagement service.
* @module api/WidgetManagementApi
* @version 1.0.0
*/
export default class WidgetManagementApi {

    /**
    * Constructs a new WidgetManagementApi. 
    * @alias module:api/WidgetManagementApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Bulk revoke tokens
     * Revoke multiple widget tokens at once
     * @param {module:model/BulkRevokeTokensRequest} bulkRevokeTokensRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BulkRevokeTokens200Response} and HTTP response
     */
    bulkRevokeTokensWithHttpInfo(bulkRevokeTokensRequest) {
      let postBody = bulkRevokeTokensRequest;
      // verify the required parameter 'bulkRevokeTokensRequest' is set
      if (bulkRevokeTokensRequest === undefined || bulkRevokeTokensRequest === null) {
        throw new Error("Missing the required parameter 'bulkRevokeTokensRequest' when calling bulkRevokeTokens");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BulkRevokeTokens200Response;
      return this.apiClient.callApi(
        '/api/v1/widget/tokens/bulk-revoke', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Bulk revoke tokens
     * Revoke multiple widget tokens at once
     * @param {module:model/BulkRevokeTokensRequest} bulkRevokeTokensRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BulkRevokeTokens200Response}
     */
    bulkRevokeTokens(bulkRevokeTokensRequest) {
      return this.bulkRevokeTokensWithHttpInfo(bulkRevokeTokensRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Generate a widget token
     * Generate a new widget token for embedding. Requires domain_token for authentication.
     * @param {module:model/GenerateAWidgetTokenRequest} generateAWidgetTokenRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GenerateAWidgetToken201Response} and HTTP response
     */
    generateAWidgetTokenWithHttpInfo(generateAWidgetTokenRequest) {
      let postBody = generateAWidgetTokenRequest;
      // verify the required parameter 'generateAWidgetTokenRequest' is set
      if (generateAWidgetTokenRequest === undefined || generateAWidgetTokenRequest === null) {
        throw new Error("Missing the required parameter 'generateAWidgetTokenRequest' when calling generateAWidgetToken");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GenerateAWidgetToken201Response;
      return this.apiClient.callApi(
        '/api/v1/widget/tokens', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Generate a widget token
     * Generate a new widget token for embedding. Requires domain_token for authentication.
     * @param {module:model/GenerateAWidgetTokenRequest} generateAWidgetTokenRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GenerateAWidgetToken201Response}
     */
    generateAWidgetToken(generateAWidgetTokenRequest) {
      return this.generateAWidgetTokenWithHttpInfo(generateAWidgetTokenRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get domain details
     * Get details of a specific registered domain
     * @param {Number} id The domain ID.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetDomainDetails200Response} and HTTP response
     */
    getDomainDetailsWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getDomainDetails");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetDomainDetails200Response;
      return this.apiClient.callApi(
        '/api/v1/widget/domains/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get domain details
     * Get details of a specific registered domain
     * @param {Number} id The domain ID.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetDomainDetails200Response}
     */
    getDomainDetails(id) {
      return this.getDomainDetailsWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get token details
     * Get details of a specific widget token
     * @param {Number} id The token ID.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetTokenDetails200Response} and HTTP response
     */
    getTokenDetailsWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTokenDetails");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetTokenDetails200Response;
      return this.apiClient.callApi(
        '/api/v1/widget/tokens/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get token details
     * Get details of a specific widget token
     * @param {Number} id The token ID.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetTokenDetails200Response}
     */
    getTokenDetails(id) {
      return this.getTokenDetailsWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List registered domains
     * Get all registered widget domains for the authenticated operator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListRegisteredDomains200Response} and HTTP response
     */
    listRegisteredDomainsWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListRegisteredDomains200Response;
      return this.apiClient.callApi(
        '/api/v1/widget/domains', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List registered domains
     * Get all registered widget domains for the authenticated operator
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListRegisteredDomains200Response}
     */
    listRegisteredDomains() {
      return this.listRegisteredDomainsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List widget tokens
     * Get all widget tokens for the authenticated operator
     * @param {Object} opts Optional parameters
     * @param {Number} [domainId] optional Filter by domain ID.
     * @param {Boolean} [active] optional Filter by active status.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListWidgetTokens200Response} and HTTP response
     */
    listWidgetTokensWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'domain_id': opts['domainId'],
        'active': opts['active']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListWidgetTokens200Response;
      return this.apiClient.callApi(
        '/api/v1/widget/tokens', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List widget tokens
     * Get all widget tokens for the authenticated operator
     * @param {Object} opts Optional parameters
     * @param {Number} opts.domainId optional Filter by domain ID.
     * @param {Boolean} opts.active optional Filter by active status.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListWidgetTokens200Response}
     */
    listWidgetTokens(opts) {
      return this.listWidgetTokensWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Regenerate domain token
     * Generate a new domain_token (invalidates all existing widget tokens)
     * @param {Number} id The domain ID.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RegenerateDomainToken200Response} and HTTP response
     */
    regenerateDomainTokenWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling regenerateDomainToken");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RegenerateDomainToken200Response;
      return this.apiClient.callApi(
        '/api/v1/widget/domains/{id}/regenerate-token', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Regenerate domain token
     * Generate a new domain_token (invalidates all existing widget tokens)
     * @param {Number} id The domain ID.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RegenerateDomainToken200Response}
     */
    regenerateDomainToken(id) {
      return this.regenerateDomainTokenWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Register a new domain
     * Register a domain that can embed widgets. Returns a domain_token used to generate widget tokens.
     * @param {module:model/RegisterANewDomainRequest} registerANewDomainRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RegisterANewDomain201Response} and HTTP response
     */
    registerANewDomainWithHttpInfo(registerANewDomainRequest) {
      let postBody = registerANewDomainRequest;
      // verify the required parameter 'registerANewDomainRequest' is set
      if (registerANewDomainRequest === undefined || registerANewDomainRequest === null) {
        throw new Error("Missing the required parameter 'registerANewDomainRequest' when calling registerANewDomain");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RegisterANewDomain201Response;
      return this.apiClient.callApi(
        '/api/v1/widget/domains', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Register a new domain
     * Register a domain that can embed widgets. Returns a domain_token used to generate widget tokens.
     * @param {module:model/RegisterANewDomainRequest} registerANewDomainRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RegisterANewDomain201Response}
     */
    registerANewDomain(registerANewDomainRequest) {
      return this.registerANewDomainWithHttpInfo(registerANewDomainRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Remove a domain
     * Remove a registered domain and revoke all its tokens
     * @param {Number} id The domain ID.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RemoveADomain200Response} and HTTP response
     */
    removeADomainWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling removeADomain");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RemoveADomain200Response;
      return this.apiClient.callApi(
        '/api/v1/widget/domains/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Remove a domain
     * Remove a registered domain and revoke all its tokens
     * @param {Number} id The domain ID.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RemoveADomain200Response}
     */
    removeADomain(id) {
      return this.removeADomainWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Revoke a token
     * Revoke a widget token (cannot be undone)
     * @param {Number} id The token ID.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RevokeAToken200Response} and HTTP response
     */
    revokeATokenWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling revokeAToken");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RevokeAToken200Response;
      return this.apiClient.callApi(
        '/api/v1/widget/tokens/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Revoke a token
     * Revoke a widget token (cannot be undone)
     * @param {Number} id The token ID.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RevokeAToken200Response}
     */
    revokeAToken(id) {
      return this.revokeATokenWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update domain settings
     * Update a registered domain's settings
     * @param {Number} id The domain ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateDomainSettingsRequest} [updateDomainSettingsRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UpdateDomainSettings200Response} and HTTP response
     */
    updateDomainSettingsWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['updateDomainSettingsRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateDomainSettings");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['default'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UpdateDomainSettings200Response;
      return this.apiClient.callApi(
        '/api/v1/widget/domains/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update domain settings
     * Update a registered domain's settings
     * @param {Number} id The domain ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateDomainSettingsRequest} opts.updateDomainSettingsRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UpdateDomainSettings200Response}
     */
    updateDomainSettings(id, opts) {
      return this.updateDomainSettingsWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
