/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameHubApi);
  }
}(this, function(expect, GameHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameHubApi.AddAContributionToAJackpotPoolRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AddAContributionToAJackpotPoolRequest', function() {
    it('should create an instance of AddAContributionToAJackpotPoolRequest', function() {
      // uncomment below and update the code to test AddAContributionToAJackpotPoolRequest
      //var instance = new GameHubApi.AddAContributionToAJackpotPoolRequest();
      //expect(instance).to.be.a(GameHubApi.AddAContributionToAJackpotPoolRequest);
    });

    it('should have the property playerId (base name: "player_id")', function() {
      // uncomment below and update the code to test the property playerId
      //var instance = new GameHubApi.AddAContributionToAJackpotPoolRequest();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new GameHubApi.AddAContributionToAJackpotPoolRequest();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new GameHubApi.AddAContributionToAJackpotPoolRequest();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new GameHubApi.AddAContributionToAJackpotPoolRequest();
      //expect(instance).to.be();
    });

    it('should have the property transactionId (base name: "transaction_id")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instance = new GameHubApi.AddAContributionToAJackpotPoolRequest();
      //expect(instance).to.be();
    });

    it('should have the property gameId (base name: "game_id")', function() {
      // uncomment below and update the code to test the property gameId
      //var instance = new GameHubApi.AddAContributionToAJackpotPoolRequest();
      //expect(instance).to.be();
    });

    it('should have the property externalGameId (base name: "external_game_id")', function() {
      // uncomment below and update the code to test the property externalGameId
      //var instance = new GameHubApi.AddAContributionToAJackpotPoolRequest();
      //expect(instance).to.be();
    });

    it('should have the property gameSessionId (base name: "game_session_id")', function() {
      // uncomment below and update the code to test the property gameSessionId
      //var instance = new GameHubApi.AddAContributionToAJackpotPoolRequest();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new GameHubApi.AddAContributionToAJackpotPoolRequest();
      //expect(instance).to.be();
    });

  });

}));
