/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameHubApi);
  }
}(this, function(expect, GameHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConfigureJackpotSettingsForTheOperatorRequest', function() {
    it('should create an instance of ConfigureJackpotSettingsForTheOperatorRequest', function() {
      // uncomment below and update the code to test ConfigureJackpotSettingsForTheOperatorRequest
      //var instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
      //expect(instance).to.be.a(GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest);
    });

    it('should have the property isEnabled (base name: "is_enabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
      //expect(instance).to.be();
    });

    it('should have the property poolTypes (base name: "pool_types")', function() {
      // uncomment below and update the code to test the property poolTypes
      //var instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
      //expect(instance).to.be();
    });

    it('should have the property casinoCutPercentage (base name: "casino_cut_percentage")', function() {
      // uncomment below and update the code to test the property casinoCutPercentage
      //var instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
      //expect(instance).to.be();
    });

    it('should have the property winnerCount (base name: "winner_count")', function() {
      // uncomment below and update the code to test the property winnerCount
      //var instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
      //expect(instance).to.be();
    });

    it('should have the property distributionMethod (base name: "distribution_method")', function() {
      // uncomment below and update the code to test the property distributionMethod
      //var instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
      //expect(instance).to.be();
    });

    it('should have the property weightCalculation (base name: "weight_calculation")', function() {
      // uncomment below and update the code to test the property weightCalculation
      //var instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
      //expect(instance).to.be();
    });

    it('should have the property prizeTiers (base name: "prize_tiers")', function() {
      // uncomment below and update the code to test the property prizeTiers
      //var instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
      //expect(instance).to.be();
    });

    it('should have the property gameFilterEnabled (base name: "game_filter_enabled")', function() {
      // uncomment below and update the code to test the property gameFilterEnabled
      //var instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
      //expect(instance).to.be();
    });

    it('should have the property webhookEnabled (base name: "webhook_enabled")', function() {
      // uncomment below and update the code to test the property webhookEnabled
      //var instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
      //expect(instance).to.be();
    });

    it('should have the property reminderHoursBefore (base name: "reminder_hours_before")', function() {
      // uncomment below and update the code to test the property reminderHoursBefore
      //var instance = new GameHubApi.ConfigureJackpotSettingsForTheOperatorRequest();
      //expect(instance).to.be();
    });

  });

}));
