/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameHubApi);
  }
}(this, function(expect, GameHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameHubApi.CreateAStandaloneFreespin201ResponseData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateAStandaloneFreespin201ResponseData', function() {
    it('should create an instance of CreateAStandaloneFreespin201ResponseData', function() {
      // uncomment below and update the code to test CreateAStandaloneFreespin201ResponseData
      //var instance = new GameHubApi.CreateAStandaloneFreespin201ResponseData();
      //expect(instance).to.be.a(GameHubApi.CreateAStandaloneFreespin201ResponseData);
    });

    it('should have the property freespinId (base name: "freespin_id")', function() {
      // uncomment below and update the code to test the property freespinId
      //var instance = new GameHubApi.CreateAStandaloneFreespin201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property playerId (base name: "player_id")', function() {
      // uncomment below and update the code to test the property playerId
      //var instance = new GameHubApi.CreateAStandaloneFreespin201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property gameId (base name: "game_id")', function() {
      // uncomment below and update the code to test the property gameId
      //var instance = new GameHubApi.CreateAStandaloneFreespin201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property totalCount (base name: "total_count")', function() {
      // uncomment below and update the code to test the property totalCount
      //var instance = new GameHubApi.CreateAStandaloneFreespin201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property betAmount (base name: "bet_amount")', function() {
      // uncomment below and update the code to test the property betAmount
      //var instance = new GameHubApi.CreateAStandaloneFreespin201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new GameHubApi.CreateAStandaloneFreespin201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property expiresAt (base name: "expires_at")', function() {
      // uncomment below and update the code to test the property expiresAt
      //var instance = new GameHubApi.CreateAStandaloneFreespin201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new GameHubApi.CreateAStandaloneFreespin201ResponseData();
      //expect(instance).to.be();
    });

  });

}));
