/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameHubApi);
  }
}(this, function(expect, GameHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameHubApi.CreateANewPromotionRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateANewPromotionRequest', function() {
    it('should create an instance of CreateANewPromotionRequest', function() {
      // uncomment below and update the code to test CreateANewPromotionRequest
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be.a(GameHubApi.CreateANewPromotionRequest);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property imageUrl (base name: "image_url")', function() {
      // uncomment below and update the code to test the property imageUrl
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property termsAndConditions (base name: "terms_and_conditions")', function() {
      // uncomment below and update the code to test the property termsAndConditions
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property promotionType (base name: "promotion_type")', function() {
      // uncomment below and update the code to test the property promotionType
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property cycleType (base name: "cycle_type")', function() {
      // uncomment below and update the code to test the property cycleType
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property startsAt (base name: "starts_at")', function() {
      // uncomment below and update the code to test the property startsAt
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property endsAt (base name: "ends_at")', function() {
      // uncomment below and update the code to test the property endsAt
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property timezone (base name: "timezone")', function() {
      // uncomment below and update the code to test the property timezone
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property prizeDistribution (base name: "prize_distribution")', function() {
      // uncomment below and update the code to test the property prizeDistribution
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property totalPrizePool (base name: "total_prize_pool")', function() {
      // uncomment below and update the code to test the property totalPrizePool
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property prizeCurrency (base name: "prize_currency")', function() {
      // uncomment below and update the code to test the property prizeCurrency
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property winnerCount (base name: "winner_count")', function() {
      // uncomment below and update the code to test the property winnerCount
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property entryConfig (base name: "entry_config")', function() {
      // uncomment below and update the code to test the property entryConfig
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property gameFilterEnabled (base name: "game_filter_enabled")', function() {
      // uncomment below and update the code to test the property gameFilterEnabled
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property producerFilterEnabled (base name: "producer_filter_enabled")', function() {
      // uncomment below and update the code to test the property producerFilterEnabled
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property webhookEnabled (base name: "webhook_enabled")', function() {
      // uncomment below and update the code to test the property webhookEnabled
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property isFeatured (base name: "is_featured")', function() {
      // uncomment below and update the code to test the property isFeatured
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property gameIds (base name: "game_ids")', function() {
      // uncomment below and update the code to test the property gameIds
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

    it('should have the property producerIds (base name: "producer_ids")', function() {
      // uncomment below and update the code to test the property producerIds
      //var instance = new GameHubApi.CreateANewPromotionRequest();
      //expect(instance).to.be();
    });

  });

}));
