/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameHubApi);
  }
}(this, function(expect, GameHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameHubApi.GenerateAWidgetToken201ResponseData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GenerateAWidgetToken201ResponseData', function() {
    it('should create an instance of GenerateAWidgetToken201ResponseData', function() {
      // uncomment below and update the code to test GenerateAWidgetToken201ResponseData
      //var instance = new GameHubApi.GenerateAWidgetToken201ResponseData();
      //expect(instance).to.be.a(GameHubApi.GenerateAWidgetToken201ResponseData);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new GameHubApi.GenerateAWidgetToken201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instance = new GameHubApi.GenerateAWidgetToken201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property widgetType (base name: "widget_type")', function() {
      // uncomment below and update the code to test the property widgetType
      //var instance = new GameHubApi.GenerateAWidgetToken201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property playerId (base name: "player_id")', function() {
      // uncomment below and update the code to test the property playerId
      //var instance = new GameHubApi.GenerateAWidgetToken201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property allowedPoolTypes (base name: "allowed_pool_types")', function() {
      // uncomment below and update the code to test the property allowedPoolTypes
      //var instance = new GameHubApi.GenerateAWidgetToken201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property expiresAt (base name: "expires_at")', function() {
      // uncomment below and update the code to test the property expiresAt
      //var instance = new GameHubApi.GenerateAWidgetToken201ResponseData();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new GameHubApi.GenerateAWidgetToken201ResponseData();
      //expect(instance).to.be();
    });

  });

}));
