/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameHubApi);
  }
}(this, function(expect, GameHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameHubApi.GetTransactionHistory200ResponseMetaSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetTransactionHistory200ResponseMetaSummary', function() {
    it('should create an instance of GetTransactionHistory200ResponseMetaSummary', function() {
      // uncomment below and update the code to test GetTransactionHistory200ResponseMetaSummary
      //var instance = new GameHubApi.GetTransactionHistory200ResponseMetaSummary();
      //expect(instance).to.be.a(GameHubApi.GetTransactionHistory200ResponseMetaSummary);
    });

    it('should have the property totalBets (base name: "total_bets")', function() {
      // uncomment below and update the code to test the property totalBets
      //var instance = new GameHubApi.GetTransactionHistory200ResponseMetaSummary();
      //expect(instance).to.be();
    });

    it('should have the property totalWins (base name: "total_wins")', function() {
      // uncomment below and update the code to test the property totalWins
      //var instance = new GameHubApi.GetTransactionHistory200ResponseMetaSummary();
      //expect(instance).to.be();
    });

    it('should have the property netResult (base name: "net_result")', function() {
      // uncomment below and update the code to test the property netResult
      //var instance = new GameHubApi.GetTransactionHistory200ResponseMetaSummary();
      //expect(instance).to.be();
    });

  });

}));
