/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameHubApi);
  }
}(this, function(expect, GameHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameHubApi.ImportExternalGamesFromJSONPasteRequestGamesInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ImportExternalGamesFromJSONPasteRequestGamesInner', function() {
    it('should create an instance of ImportExternalGamesFromJSONPasteRequestGamesInner', function() {
      // uncomment below and update the code to test ImportExternalGamesFromJSONPasteRequestGamesInner
      //var instance = new GameHubApi.ImportExternalGamesFromJSONPasteRequestGamesInner();
      //expect(instance).to.be.a(GameHubApi.ImportExternalGamesFromJSONPasteRequestGamesInner);
    });

    it('should have the property externalGameId (base name: "external_game_id")', function() {
      // uncomment below and update the code to test the property externalGameId
      //var instance = new GameHubApi.ImportExternalGamesFromJSONPasteRequestGamesInner();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new GameHubApi.ImportExternalGamesFromJSONPasteRequestGamesInner();
      //expect(instance).to.be();
    });

    it('should have the property producerName (base name: "producer_name")', function() {
      // uncomment below and update the code to test the property producerName
      //var instance = new GameHubApi.ImportExternalGamesFromJSONPasteRequestGamesInner();
      //expect(instance).to.be();
    });

    it('should have the property imageUrl (base name: "image_url")', function() {
      // uncomment below and update the code to test the property imageUrl
      //var instance = new GameHubApi.ImportExternalGamesFromJSONPasteRequestGamesInner();
      //expect(instance).to.be();
    });

  });

}));
