/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameHubApi);
  }
}(this, function(expect, GameHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameHubApi.ListOperatorsJackpotPoolsRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListOperatorsJackpotPoolsRequest', function() {
    it('should create an instance of ListOperatorsJackpotPoolsRequest', function() {
      // uncomment below and update the code to test ListOperatorsJackpotPoolsRequest
      //var instance = new GameHubApi.ListOperatorsJackpotPoolsRequest();
      //expect(instance).to.be.a(GameHubApi.ListOperatorsJackpotPoolsRequest);
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new GameHubApi.ListOperatorsJackpotPoolsRequest();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new GameHubApi.ListOperatorsJackpotPoolsRequest();
      //expect(instance).to.be();
    });

    it('should have the property poolType (base name: "pool_type")', function() {
      // uncomment below and update the code to test the property poolType
      //var instance = new GameHubApi.ListOperatorsJackpotPoolsRequest();
      //expect(instance).to.be();
    });

  });

}));
