/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameHubApi);
  }
}(this, function(expect, GameHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameHubApi.ListGames200ResponseDataInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListGames200ResponseDataInner', function() {
    it('should create an instance of ListGames200ResponseDataInner', function() {
      // uncomment below and update the code to test ListGames200ResponseDataInner
      //var instance = new GameHubApi.ListGames200ResponseDataInner();
      //expect(instance).to.be.a(GameHubApi.ListGames200ResponseDataInner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new GameHubApi.ListGames200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new GameHubApi.ListGames200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property producer (base name: "producer")', function() {
      // uncomment below and update the code to test the property producer
      //var instance = new GameHubApi.ListGames200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new GameHubApi.ListGames200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new GameHubApi.ListGames200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property imageUrl (base name: "image_url")', function() {
      // uncomment below and update the code to test the property imageUrl
      //var instance = new GameHubApi.ListGames200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property currenciesSupported (base name: "currencies_supported")', function() {
      // uncomment below and update the code to test the property currenciesSupported
      //var instance = new GameHubApi.ListGames200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property countriesSupported (base name: "countries_supported")', function() {
      // uncomment below and update the code to test the property countriesSupported
      //var instance = new GameHubApi.ListGames200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property hasDemo (base name: "has_demo")', function() {
      // uncomment below and update the code to test the property hasDemo
      //var instance = new GameHubApi.ListGames200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property hasFreespins (base name: "has_freespins")', function() {
      // uncomment below and update the code to test the property hasFreespins
      //var instance = new GameHubApi.ListGames200ResponseDataInner();
      //expect(instance).to.be();
    });

  });

}));
