/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameHubApi);
  }
}(this, function(expect, GameHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameHubApi.PostApiV1GameTransactionsExportRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostApiV1GameTransactionsExportRequest', function() {
    it('should create an instance of PostApiV1GameTransactionsExportRequest', function() {
      // uncomment below and update the code to test PostApiV1GameTransactionsExportRequest
      //var instance = new GameHubApi.PostApiV1GameTransactionsExportRequest();
      //expect(instance).to.be.a(GameHubApi.PostApiV1GameTransactionsExportRequest);
    });

    it('should have the property format (base name: "format")', function() {
      // uncomment below and update the code to test the property format
      //var instance = new GameHubApi.PostApiV1GameTransactionsExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property fromDate (base name: "from_date")', function() {
      // uncomment below and update the code to test the property fromDate
      //var instance = new GameHubApi.PostApiV1GameTransactionsExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property toDate (base name: "to_date")', function() {
      // uncomment below and update the code to test the property toDate
      //var instance = new GameHubApi.PostApiV1GameTransactionsExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property playerId (base name: "player_id")', function() {
      // uncomment below and update the code to test the property playerId
      //var instance = new GameHubApi.PostApiV1GameTransactionsExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property gameId (base name: "game_id")', function() {
      // uncomment below and update the code to test the property gameId
      //var instance = new GameHubApi.PostApiV1GameTransactionsExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new GameHubApi.PostApiV1GameTransactionsExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property includeSummary (base name: "include_summary")', function() {
      // uncomment below and update the code to test the property includeSummary
      //var instance = new GameHubApi.PostApiV1GameTransactionsExportRequest();
      //expect(instance).to.be();
    });

    it('should have the property async (base name: "async")', function() {
      // uncomment below and update the code to test the property async
      //var instance = new GameHubApi.PostApiV1GameTransactionsExportRequest();
      //expect(instance).to.be();
    });

  });

}));
