/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameHubApi);
  }
}(this, function(expect, GameHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameHubApi.StartAMultiSessionRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StartAMultiSessionRequest', function() {
    it('should create an instance of StartAMultiSessionRequest', function() {
      // uncomment below and update the code to test StartAMultiSessionRequest
      //var instance = new GameHubApi.StartAMultiSessionRequest();
      //expect(instance).to.be.a(GameHubApi.StartAMultiSessionRequest);
    });

    it('should have the property playerId (base name: "player_id")', function() {
      // uncomment below and update the code to test the property playerId
      //var instance = new GameHubApi.StartAMultiSessionRequest();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new GameHubApi.StartAMultiSessionRequest();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "country_code")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instance = new GameHubApi.StartAMultiSessionRequest();
      //expect(instance).to.be();
    });

    it('should have the property ipAddress (base name: "ip_address")', function() {
      // uncomment below and update the code to test the property ipAddress
      //var instance = new GameHubApi.StartAMultiSessionRequest();
      //expect(instance).to.be();
    });

    it('should have the property gameIds (base name: "game_ids")', function() {
      // uncomment below and update the code to test the property gameIds
      //var instance = new GameHubApi.StartAMultiSessionRequest();
      //expect(instance).to.be();
    });

    it('should have the property locale (base name: "locale")', function() {
      // uncomment below and update the code to test the property locale
      //var instance = new GameHubApi.StartAMultiSessionRequest();
      //expect(instance).to.be();
    });

    it('should have the property device (base name: "device")', function() {
      // uncomment below and update the code to test the property device
      //var instance = new GameHubApi.StartAMultiSessionRequest();
      //expect(instance).to.be();
    });

  });

}));
