/**
 * Game Aggregator API Documentation
 * Universal API for casino operators to access games from multiple providers through a single integration.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddAContributionToAJackpotPoolRequest from './model/AddAContributionToAJackpotPoolRequest';
import AddGamesToAJackpotPoolTypeRequest from './model/AddGamesToAJackpotPoolTypeRequest';
import BulkCreateExternalGamesFromJSONArrayRequest from './model/BulkCreateExternalGamesFromJSONArrayRequest';
import BulkDeleteExternalGamesByIDsRequest from './model/BulkDeleteExternalGamesByIDsRequest';
import BulkRevokeTokens200Response from './model/BulkRevokeTokens200Response';
import BulkRevokeTokensRequest from './model/BulkRevokeTokensRequest';
import CancelAStandaloneFreespin200Response from './model/CancelAStandaloneFreespin200Response';
import CancelAStandaloneFreespin200ResponseData from './model/CancelAStandaloneFreespin200ResponseData';
import CancelAStandaloneFreespin401Response from './model/CancelAStandaloneFreespin401Response';
import CancelAStandaloneFreespin404Response from './model/CancelAStandaloneFreespin404Response';
import CancelAStandaloneFreespin409Response from './model/CancelAStandaloneFreespin409Response';
import CancelAStandaloneFreespin500Response from './model/CancelAStandaloneFreespin500Response';
import CancelAStandaloneFreespinRequest from './model/CancelAStandaloneFreespinRequest';
import ConfigureJackpotSettingsForTheOperatorRequest from './model/ConfigureJackpotSettingsForTheOperatorRequest';
import ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner from './model/ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner';
import ConfigureLiveModeSettingsForAPoolRequest from './model/ConfigureLiveModeSettingsForAPoolRequest';
import CreateANewPromotionRequest from './model/CreateANewPromotionRequest';
import CreateASingleExternalGameRequest from './model/CreateASingleExternalGameRequest';
import CreateAStandaloneFreespin201Response from './model/CreateAStandaloneFreespin201Response';
import CreateAStandaloneFreespin201ResponseData from './model/CreateAStandaloneFreespin201ResponseData';
import CreateAStandaloneFreespin400Response from './model/CreateAStandaloneFreespin400Response';
import CreateAStandaloneFreespin403Response from './model/CreateAStandaloneFreespin403Response';
import CreateAStandaloneFreespin404Response from './model/CreateAStandaloneFreespin404Response';
import CreateAStandaloneFreespin409Response from './model/CreateAStandaloneFreespin409Response';
import CreateAStandaloneFreespin503Response from './model/CreateAStandaloneFreespin503Response';
import CreateAStandaloneFreespinRequest from './model/CreateAStandaloneFreespinRequest';
import CreateATargetedPlayerConfigurationRequest from './model/CreateATargetedPlayerConfigurationRequest';
import Datetime from './model/Datetime';
import EndAGameSession200Response from './model/EndAGameSession200Response';
import EndMultiSession200Response from './model/EndMultiSession200Response';
import GenerateAWidgetToken201Response from './model/GenerateAWidgetToken201Response';
import GenerateAWidgetToken201ResponseData from './model/GenerateAWidgetToken201ResponseData';
import GenerateAWidgetToken400Response from './model/GenerateAWidgetToken400Response';
import GenerateAWidgetToken401Response from './model/GenerateAWidgetToken401Response';
import GenerateAWidgetTokenRequest from './model/GenerateAWidgetTokenRequest';
import GetApiV1Producers401Response from './model/GetApiV1Producers401Response';
import GetApiV1TransactionExportsExportIdDownload500Response from './model/GetApiV1TransactionExportsExportIdDownload500Response';
import GetDomainDetails200Response from './model/GetDomainDetails200Response';
import GetDomainDetails200ResponseData from './model/GetDomainDetails200ResponseData';
import GetGamesForAPoolTypeOrAllPoolTypesRequest from './model/GetGamesForAPoolTypeOrAllPoolTypesRequest';
import GetMultiSessionStatus200Response from './model/GetMultiSessionStatus200Response';
import GetMultiSessionStatus200ResponseData from './model/GetMultiSessionStatus200ResponseData';
import GetMultiSessionStatus200ResponseDataGamesInner from './model/GetMultiSessionStatus200ResponseDataGamesInner';
import GetMultiSessionStatus404Response from './model/GetMultiSessionStatus404Response';
import GetPlayerContributionHistoryRequest from './model/GetPlayerContributionHistoryRequest';
import GetSessionStatus200Response from './model/GetSessionStatus200Response';
import GetSessionStatus200ResponseData from './model/GetSessionStatus200ResponseData';
import GetSessionStatus200ResponseDataGame from './model/GetSessionStatus200ResponseDataGame';
import GetSessionStatus404Response from './model/GetSessionStatus404Response';
import GetTokenDetails200Response from './model/GetTokenDetails200Response';
import GetTokenDetails200ResponseData from './model/GetTokenDetails200ResponseData';
import GetTransactionDetails404Response from './model/GetTransactionDetails404Response';
import GetTransactionHistory200Response from './model/GetTransactionHistory200Response';
import GetTransactionHistory200ResponseDataInner from './model/GetTransactionHistory200ResponseDataInner';
import GetTransactionHistory200ResponseMeta from './model/GetTransactionHistory200ResponseMeta';
import GetTransactionHistory200ResponseMetaSummary from './model/GetTransactionHistory200ResponseMetaSummary';
import ImportExternalGamesFromJSONPasteRequest from './model/ImportExternalGamesFromJSONPasteRequest';
import ImportExternalGamesFromJSONPasteRequestGamesInner from './model/ImportExternalGamesFromJSONPasteRequestGamesInner';
import ListExternalGamesForOperatorRequest from './model/ListExternalGamesForOperatorRequest';
import ListGames200Response from './model/ListGames200Response';
import ListGames200ResponseDataInner from './model/ListGames200ResponseDataInner';
import ListGames200ResponseMeta from './model/ListGames200ResponseMeta';
import ListGamesRequest from './model/ListGamesRequest';
import ListOperatorsJackpotPoolsRequest from './model/ListOperatorsJackpotPoolsRequest';
import ListRegisteredDomains200Response from './model/ListRegisteredDomains200Response';
import ListRegisteredDomains200ResponseDataInner from './model/ListRegisteredDomains200ResponseDataInner';
import ListTargetedPlayersForOperatorRequest from './model/ListTargetedPlayersForOperatorRequest';
import ListWidgetTokens200Response from './model/ListWidgetTokens200Response';
import ListWidgetTokens200ResponseDataInner from './model/ListWidgetTokens200ResponseDataInner';
import ManageGamesForAPromotionRequest from './model/ManageGamesForAPromotionRequest';
import Numeric from './model/Numeric';
import PostApiV1GameTransactionsExportRequest from './model/PostApiV1GameTransactionsExportRequest';
import RegenerateDomainToken200Response from './model/RegenerateDomainToken200Response';
import RegenerateDomainToken200ResponseData from './model/RegenerateDomainToken200ResponseData';
import RegisterANewDomain201Response from './model/RegisterANewDomain201Response';
import RegisterANewDomain201ResponseData from './model/RegisterANewDomain201ResponseData';
import RegisterANewDomain422Response from './model/RegisterANewDomain422Response';
import RegisterANewDomainRequest from './model/RegisterANewDomainRequest';
import RemoveADomain200Response from './model/RemoveADomain200Response';
import RemoveGamesFromAJackpotPoolTypeRequest from './model/RemoveGamesFromAJackpotPoolTypeRequest';
import RevokeAToken200Response from './model/RevokeAToken200Response';
import SetGrandPrizeExpirationDateRequest from './model/SetGrandPrizeExpirationDateRequest';
import StartAGameSession201Response from './model/StartAGameSession201Response';
import StartAGameSession201ResponseData from './model/StartAGameSession201ResponseData';
import StartAGameSession400Response from './model/StartAGameSession400Response';
import StartAGameSession503Response from './model/StartAGameSession503Response';
import StartAGameSessionRequest from './model/StartAGameSessionRequest';
import StartAMultiSession201Response from './model/StartAMultiSession201Response';
import StartAMultiSession201ResponseData from './model/StartAMultiSession201ResponseData';
import StartAMultiSession201ResponseDataGamesInner from './model/StartAMultiSession201ResponseDataGamesInner';
import StartAMultiSession400Response from './model/StartAMultiSession400Response';
import StartAMultiSessionRequest from './model/StartAMultiSessionRequest';
import UpdateAPromotionRequest from './model/UpdateAPromotionRequest';
import UpdateAnExternalGameRequest from './model/UpdateAnExternalGameRequest';
import UpdateDomainSettings200Response from './model/UpdateDomainSettings200Response';
import UpdateDomainSettings200ResponseData from './model/UpdateDomainSettings200ResponseData';
import UpdateDomainSettingsRequest from './model/UpdateDomainSettingsRequest';
import EndpointsApi from './api/EndpointsApi';
import FreespinsApi from './api/FreespinsApi';
import GameSessionsApi from './api/GameSessionsApi';
import GameTransactionsApi from './api/GameTransactionsApi';
import GamesApi from './api/GamesApi';
import MultiSessionsApi from './api/MultiSessionsApi';
import WidgetManagementApi from './api/WidgetManagementApi';


/**
* Universal API for casino operators to access games from multiple providers through a single integration..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var IPlayGamesApi = require('index'); // See note below*.
* var xxxSvc = new IPlayGamesApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new IPlayGamesApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new IPlayGamesApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new IPlayGamesApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddAContributionToAJackpotPoolRequest model constructor.
     * @property {module:model/AddAContributionToAJackpotPoolRequest}
     */
    AddAContributionToAJackpotPoolRequest,

    /**
     * The AddGamesToAJackpotPoolTypeRequest model constructor.
     * @property {module:model/AddGamesToAJackpotPoolTypeRequest}
     */
    AddGamesToAJackpotPoolTypeRequest,

    /**
     * The BulkCreateExternalGamesFromJSONArrayRequest model constructor.
     * @property {module:model/BulkCreateExternalGamesFromJSONArrayRequest}
     */
    BulkCreateExternalGamesFromJSONArrayRequest,

    /**
     * The BulkDeleteExternalGamesByIDsRequest model constructor.
     * @property {module:model/BulkDeleteExternalGamesByIDsRequest}
     */
    BulkDeleteExternalGamesByIDsRequest,

    /**
     * The BulkRevokeTokens200Response model constructor.
     * @property {module:model/BulkRevokeTokens200Response}
     */
    BulkRevokeTokens200Response,

    /**
     * The BulkRevokeTokensRequest model constructor.
     * @property {module:model/BulkRevokeTokensRequest}
     */
    BulkRevokeTokensRequest,

    /**
     * The CancelAStandaloneFreespin200Response model constructor.
     * @property {module:model/CancelAStandaloneFreespin200Response}
     */
    CancelAStandaloneFreespin200Response,

    /**
     * The CancelAStandaloneFreespin200ResponseData model constructor.
     * @property {module:model/CancelAStandaloneFreespin200ResponseData}
     */
    CancelAStandaloneFreespin200ResponseData,

    /**
     * The CancelAStandaloneFreespin401Response model constructor.
     * @property {module:model/CancelAStandaloneFreespin401Response}
     */
    CancelAStandaloneFreespin401Response,

    /**
     * The CancelAStandaloneFreespin404Response model constructor.
     * @property {module:model/CancelAStandaloneFreespin404Response}
     */
    CancelAStandaloneFreespin404Response,

    /**
     * The CancelAStandaloneFreespin409Response model constructor.
     * @property {module:model/CancelAStandaloneFreespin409Response}
     */
    CancelAStandaloneFreespin409Response,

    /**
     * The CancelAStandaloneFreespin500Response model constructor.
     * @property {module:model/CancelAStandaloneFreespin500Response}
     */
    CancelAStandaloneFreespin500Response,

    /**
     * The CancelAStandaloneFreespinRequest model constructor.
     * @property {module:model/CancelAStandaloneFreespinRequest}
     */
    CancelAStandaloneFreespinRequest,

    /**
     * The ConfigureJackpotSettingsForTheOperatorRequest model constructor.
     * @property {module:model/ConfigureJackpotSettingsForTheOperatorRequest}
     */
    ConfigureJackpotSettingsForTheOperatorRequest,

    /**
     * The ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner model constructor.
     * @property {module:model/ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner}
     */
    ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner,

    /**
     * The ConfigureLiveModeSettingsForAPoolRequest model constructor.
     * @property {module:model/ConfigureLiveModeSettingsForAPoolRequest}
     */
    ConfigureLiveModeSettingsForAPoolRequest,

    /**
     * The CreateANewPromotionRequest model constructor.
     * @property {module:model/CreateANewPromotionRequest}
     */
    CreateANewPromotionRequest,

    /**
     * The CreateASingleExternalGameRequest model constructor.
     * @property {module:model/CreateASingleExternalGameRequest}
     */
    CreateASingleExternalGameRequest,

    /**
     * The CreateAStandaloneFreespin201Response model constructor.
     * @property {module:model/CreateAStandaloneFreespin201Response}
     */
    CreateAStandaloneFreespin201Response,

    /**
     * The CreateAStandaloneFreespin201ResponseData model constructor.
     * @property {module:model/CreateAStandaloneFreespin201ResponseData}
     */
    CreateAStandaloneFreespin201ResponseData,

    /**
     * The CreateAStandaloneFreespin400Response model constructor.
     * @property {module:model/CreateAStandaloneFreespin400Response}
     */
    CreateAStandaloneFreespin400Response,

    /**
     * The CreateAStandaloneFreespin403Response model constructor.
     * @property {module:model/CreateAStandaloneFreespin403Response}
     */
    CreateAStandaloneFreespin403Response,

    /**
     * The CreateAStandaloneFreespin404Response model constructor.
     * @property {module:model/CreateAStandaloneFreespin404Response}
     */
    CreateAStandaloneFreespin404Response,

    /**
     * The CreateAStandaloneFreespin409Response model constructor.
     * @property {module:model/CreateAStandaloneFreespin409Response}
     */
    CreateAStandaloneFreespin409Response,

    /**
     * The CreateAStandaloneFreespin503Response model constructor.
     * @property {module:model/CreateAStandaloneFreespin503Response}
     */
    CreateAStandaloneFreespin503Response,

    /**
     * The CreateAStandaloneFreespinRequest model constructor.
     * @property {module:model/CreateAStandaloneFreespinRequest}
     */
    CreateAStandaloneFreespinRequest,

    /**
     * The CreateATargetedPlayerConfigurationRequest model constructor.
     * @property {module:model/CreateATargetedPlayerConfigurationRequest}
     */
    CreateATargetedPlayerConfigurationRequest,

    /**
     * The Datetime model constructor.
     * @property {module:model/Datetime}
     */
    Datetime,

    /**
     * The EndAGameSession200Response model constructor.
     * @property {module:model/EndAGameSession200Response}
     */
    EndAGameSession200Response,

    /**
     * The EndMultiSession200Response model constructor.
     * @property {module:model/EndMultiSession200Response}
     */
    EndMultiSession200Response,

    /**
     * The GenerateAWidgetToken201Response model constructor.
     * @property {module:model/GenerateAWidgetToken201Response}
     */
    GenerateAWidgetToken201Response,

    /**
     * The GenerateAWidgetToken201ResponseData model constructor.
     * @property {module:model/GenerateAWidgetToken201ResponseData}
     */
    GenerateAWidgetToken201ResponseData,

    /**
     * The GenerateAWidgetToken400Response model constructor.
     * @property {module:model/GenerateAWidgetToken400Response}
     */
    GenerateAWidgetToken400Response,

    /**
     * The GenerateAWidgetToken401Response model constructor.
     * @property {module:model/GenerateAWidgetToken401Response}
     */
    GenerateAWidgetToken401Response,

    /**
     * The GenerateAWidgetTokenRequest model constructor.
     * @property {module:model/GenerateAWidgetTokenRequest}
     */
    GenerateAWidgetTokenRequest,

    /**
     * The GetApiV1Producers401Response model constructor.
     * @property {module:model/GetApiV1Producers401Response}
     */
    GetApiV1Producers401Response,

    /**
     * The GetApiV1TransactionExportsExportIdDownload500Response model constructor.
     * @property {module:model/GetApiV1TransactionExportsExportIdDownload500Response}
     */
    GetApiV1TransactionExportsExportIdDownload500Response,

    /**
     * The GetDomainDetails200Response model constructor.
     * @property {module:model/GetDomainDetails200Response}
     */
    GetDomainDetails200Response,

    /**
     * The GetDomainDetails200ResponseData model constructor.
     * @property {module:model/GetDomainDetails200ResponseData}
     */
    GetDomainDetails200ResponseData,

    /**
     * The GetGamesForAPoolTypeOrAllPoolTypesRequest model constructor.
     * @property {module:model/GetGamesForAPoolTypeOrAllPoolTypesRequest}
     */
    GetGamesForAPoolTypeOrAllPoolTypesRequest,

    /**
     * The GetMultiSessionStatus200Response model constructor.
     * @property {module:model/GetMultiSessionStatus200Response}
     */
    GetMultiSessionStatus200Response,

    /**
     * The GetMultiSessionStatus200ResponseData model constructor.
     * @property {module:model/GetMultiSessionStatus200ResponseData}
     */
    GetMultiSessionStatus200ResponseData,

    /**
     * The GetMultiSessionStatus200ResponseDataGamesInner model constructor.
     * @property {module:model/GetMultiSessionStatus200ResponseDataGamesInner}
     */
    GetMultiSessionStatus200ResponseDataGamesInner,

    /**
     * The GetMultiSessionStatus404Response model constructor.
     * @property {module:model/GetMultiSessionStatus404Response}
     */
    GetMultiSessionStatus404Response,

    /**
     * The GetPlayerContributionHistoryRequest model constructor.
     * @property {module:model/GetPlayerContributionHistoryRequest}
     */
    GetPlayerContributionHistoryRequest,

    /**
     * The GetSessionStatus200Response model constructor.
     * @property {module:model/GetSessionStatus200Response}
     */
    GetSessionStatus200Response,

    /**
     * The GetSessionStatus200ResponseData model constructor.
     * @property {module:model/GetSessionStatus200ResponseData}
     */
    GetSessionStatus200ResponseData,

    /**
     * The GetSessionStatus200ResponseDataGame model constructor.
     * @property {module:model/GetSessionStatus200ResponseDataGame}
     */
    GetSessionStatus200ResponseDataGame,

    /**
     * The GetSessionStatus404Response model constructor.
     * @property {module:model/GetSessionStatus404Response}
     */
    GetSessionStatus404Response,

    /**
     * The GetTokenDetails200Response model constructor.
     * @property {module:model/GetTokenDetails200Response}
     */
    GetTokenDetails200Response,

    /**
     * The GetTokenDetails200ResponseData model constructor.
     * @property {module:model/GetTokenDetails200ResponseData}
     */
    GetTokenDetails200ResponseData,

    /**
     * The GetTransactionDetails404Response model constructor.
     * @property {module:model/GetTransactionDetails404Response}
     */
    GetTransactionDetails404Response,

    /**
     * The GetTransactionHistory200Response model constructor.
     * @property {module:model/GetTransactionHistory200Response}
     */
    GetTransactionHistory200Response,

    /**
     * The GetTransactionHistory200ResponseDataInner model constructor.
     * @property {module:model/GetTransactionHistory200ResponseDataInner}
     */
    GetTransactionHistory200ResponseDataInner,

    /**
     * The GetTransactionHistory200ResponseMeta model constructor.
     * @property {module:model/GetTransactionHistory200ResponseMeta}
     */
    GetTransactionHistory200ResponseMeta,

    /**
     * The GetTransactionHistory200ResponseMetaSummary model constructor.
     * @property {module:model/GetTransactionHistory200ResponseMetaSummary}
     */
    GetTransactionHistory200ResponseMetaSummary,

    /**
     * The ImportExternalGamesFromJSONPasteRequest model constructor.
     * @property {module:model/ImportExternalGamesFromJSONPasteRequest}
     */
    ImportExternalGamesFromJSONPasteRequest,

    /**
     * The ImportExternalGamesFromJSONPasteRequestGamesInner model constructor.
     * @property {module:model/ImportExternalGamesFromJSONPasteRequestGamesInner}
     */
    ImportExternalGamesFromJSONPasteRequestGamesInner,

    /**
     * The ListExternalGamesForOperatorRequest model constructor.
     * @property {module:model/ListExternalGamesForOperatorRequest}
     */
    ListExternalGamesForOperatorRequest,

    /**
     * The ListGames200Response model constructor.
     * @property {module:model/ListGames200Response}
     */
    ListGames200Response,

    /**
     * The ListGames200ResponseDataInner model constructor.
     * @property {module:model/ListGames200ResponseDataInner}
     */
    ListGames200ResponseDataInner,

    /**
     * The ListGames200ResponseMeta model constructor.
     * @property {module:model/ListGames200ResponseMeta}
     */
    ListGames200ResponseMeta,

    /**
     * The ListGamesRequest model constructor.
     * @property {module:model/ListGamesRequest}
     */
    ListGamesRequest,

    /**
     * The ListOperatorsJackpotPoolsRequest model constructor.
     * @property {module:model/ListOperatorsJackpotPoolsRequest}
     */
    ListOperatorsJackpotPoolsRequest,

    /**
     * The ListRegisteredDomains200Response model constructor.
     * @property {module:model/ListRegisteredDomains200Response}
     */
    ListRegisteredDomains200Response,

    /**
     * The ListRegisteredDomains200ResponseDataInner model constructor.
     * @property {module:model/ListRegisteredDomains200ResponseDataInner}
     */
    ListRegisteredDomains200ResponseDataInner,

    /**
     * The ListTargetedPlayersForOperatorRequest model constructor.
     * @property {module:model/ListTargetedPlayersForOperatorRequest}
     */
    ListTargetedPlayersForOperatorRequest,

    /**
     * The ListWidgetTokens200Response model constructor.
     * @property {module:model/ListWidgetTokens200Response}
     */
    ListWidgetTokens200Response,

    /**
     * The ListWidgetTokens200ResponseDataInner model constructor.
     * @property {module:model/ListWidgetTokens200ResponseDataInner}
     */
    ListWidgetTokens200ResponseDataInner,

    /**
     * The ManageGamesForAPromotionRequest model constructor.
     * @property {module:model/ManageGamesForAPromotionRequest}
     */
    ManageGamesForAPromotionRequest,

    /**
     * The Numeric model constructor.
     * @property {module:model/Numeric}
     */
    Numeric,

    /**
     * The PostApiV1GameTransactionsExportRequest model constructor.
     * @property {module:model/PostApiV1GameTransactionsExportRequest}
     */
    PostApiV1GameTransactionsExportRequest,

    /**
     * The RegenerateDomainToken200Response model constructor.
     * @property {module:model/RegenerateDomainToken200Response}
     */
    RegenerateDomainToken200Response,

    /**
     * The RegenerateDomainToken200ResponseData model constructor.
     * @property {module:model/RegenerateDomainToken200ResponseData}
     */
    RegenerateDomainToken200ResponseData,

    /**
     * The RegisterANewDomain201Response model constructor.
     * @property {module:model/RegisterANewDomain201Response}
     */
    RegisterANewDomain201Response,

    /**
     * The RegisterANewDomain201ResponseData model constructor.
     * @property {module:model/RegisterANewDomain201ResponseData}
     */
    RegisterANewDomain201ResponseData,

    /**
     * The RegisterANewDomain422Response model constructor.
     * @property {module:model/RegisterANewDomain422Response}
     */
    RegisterANewDomain422Response,

    /**
     * The RegisterANewDomainRequest model constructor.
     * @property {module:model/RegisterANewDomainRequest}
     */
    RegisterANewDomainRequest,

    /**
     * The RemoveADomain200Response model constructor.
     * @property {module:model/RemoveADomain200Response}
     */
    RemoveADomain200Response,

    /**
     * The RemoveGamesFromAJackpotPoolTypeRequest model constructor.
     * @property {module:model/RemoveGamesFromAJackpotPoolTypeRequest}
     */
    RemoveGamesFromAJackpotPoolTypeRequest,

    /**
     * The RevokeAToken200Response model constructor.
     * @property {module:model/RevokeAToken200Response}
     */
    RevokeAToken200Response,

    /**
     * The SetGrandPrizeExpirationDateRequest model constructor.
     * @property {module:model/SetGrandPrizeExpirationDateRequest}
     */
    SetGrandPrizeExpirationDateRequest,

    /**
     * The StartAGameSession201Response model constructor.
     * @property {module:model/StartAGameSession201Response}
     */
    StartAGameSession201Response,

    /**
     * The StartAGameSession201ResponseData model constructor.
     * @property {module:model/StartAGameSession201ResponseData}
     */
    StartAGameSession201ResponseData,

    /**
     * The StartAGameSession400Response model constructor.
     * @property {module:model/StartAGameSession400Response}
     */
    StartAGameSession400Response,

    /**
     * The StartAGameSession503Response model constructor.
     * @property {module:model/StartAGameSession503Response}
     */
    StartAGameSession503Response,

    /**
     * The StartAGameSessionRequest model constructor.
     * @property {module:model/StartAGameSessionRequest}
     */
    StartAGameSessionRequest,

    /**
     * The StartAMultiSession201Response model constructor.
     * @property {module:model/StartAMultiSession201Response}
     */
    StartAMultiSession201Response,

    /**
     * The StartAMultiSession201ResponseData model constructor.
     * @property {module:model/StartAMultiSession201ResponseData}
     */
    StartAMultiSession201ResponseData,

    /**
     * The StartAMultiSession201ResponseDataGamesInner model constructor.
     * @property {module:model/StartAMultiSession201ResponseDataGamesInner}
     */
    StartAMultiSession201ResponseDataGamesInner,

    /**
     * The StartAMultiSession400Response model constructor.
     * @property {module:model/StartAMultiSession400Response}
     */
    StartAMultiSession400Response,

    /**
     * The StartAMultiSessionRequest model constructor.
     * @property {module:model/StartAMultiSessionRequest}
     */
    StartAMultiSessionRequest,

    /**
     * The UpdateAPromotionRequest model constructor.
     * @property {module:model/UpdateAPromotionRequest}
     */
    UpdateAPromotionRequest,

    /**
     * The UpdateAnExternalGameRequest model constructor.
     * @property {module:model/UpdateAnExternalGameRequest}
     */
    UpdateAnExternalGameRequest,

    /**
     * The UpdateDomainSettings200Response model constructor.
     * @property {module:model/UpdateDomainSettings200Response}
     */
    UpdateDomainSettings200Response,

    /**
     * The UpdateDomainSettings200ResponseData model constructor.
     * @property {module:model/UpdateDomainSettings200ResponseData}
     */
    UpdateDomainSettings200ResponseData,

    /**
     * The UpdateDomainSettingsRequest model constructor.
     * @property {module:model/UpdateDomainSettingsRequest}
     */
    UpdateDomainSettingsRequest,

    /**
    * The EndpointsApi service constructor.
    * @property {module:api/EndpointsApi}
    */
    EndpointsApi,

    /**
    * The FreespinsApi service constructor.
    * @property {module:api/FreespinsApi}
    */
    FreespinsApi,

    /**
    * The GameSessionsApi service constructor.
    * @property {module:api/GameSessionsApi}
    */
    GameSessionsApi,

    /**
    * The GameTransactionsApi service constructor.
    * @property {module:api/GameTransactionsApi}
    */
    GameTransactionsApi,

    /**
    * The GamesApi service constructor.
    * @property {module:api/GamesApi}
    */
    GamesApi,

    /**
    * The MultiSessionsApi service constructor.
    * @property {module:api/MultiSessionsApi}
    */
    MultiSessionsApi,

    /**
    * The WidgetManagementApi service constructor.
    * @property {module:api/WidgetManagementApi}
    */
    WidgetManagementApi
};
